stages:
  aggregate:
    cmd: >-
      python aggregate-ml.py -d merged-stats.duckdb ML100K ML1M ML10M ML20M
      ML25M ML32M
    deps:
      - aggregate-ml.py
      - ML100K/ratings.duckdb
      - ML1M/ratings.duckdb
      - ML10M/ratings.duckdb
      - ML20M/ratings.duckdb
      - ML25M/ratings.duckdb
      - ML32M/ratings.duckdb
    outs:
      - merged-stats.duckdb
