stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/fixed/als-biased-default
      - runs/fixed/als-implicit-default
      - runs/fixed/bias-default
      - runs/fixed/flexmf-bpr-default
      - runs/fixed/flexmf-explicit-default
      - runs/fixed/flexmf-logistic-default
      - runs/fixed/flexmf-warp-default
      - runs/fixed/popular-default
      - runs/fixed/als-biased-optuna-best
      - runs/fixed/als-implicit-optuna-best
      - runs/fixed/bias-optuna-best
      - runs/fixed/flexmf-bpr-optuna-best
      - runs/fixed/flexmf-explicit-optuna-best
      - runs/fixed/flexmf-logistic-optuna-best
      - runs/fixed/flexmf-warp-optuna-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  export-test-qrels:
    cmd: lenskit codex trec export qrels -o splits/fixed/test.qrels.gz splits/fixed/test/test.parquet
    deps:
      - splits/fixed/test/test.parquet
    outs:
      - splits/fixed/test.qrels.gz
  export-valid-qrels:
    cmd: lenskit codex trec export qrels -o splits/fixed/valid.qrels.gz splits/fixed/valid/test.parquet
    deps:
      - splits/fixed/valid/test.parquet
    outs:
      - splits/fixed/valid.qrels.gz
  import-test-test:
    cmd: lenskit data convert --amazon --item-lists ../data/Musical_Instruments.test.csv.gz
      splits/fixed/test/test.parquet
    deps:
      - ../data/Musical_Instruments.test.csv.gz
    outs:
      - splits/fixed/test/test.parquet
  import-test-train:
    cmd: lenskit data convert --amazon ../data/Musical_Instruments.train.csv.gz ../data/Musical_Instruments.valid.csv.gz
      splits/fixed/test/train.dataset
    deps:
      - ../data/Musical_Instruments.train.csv.gz
      - ../data/Musical_Instruments.valid.csv.gz
    outs:
      - splits/fixed/test/train.dataset
  import-valid-test:
    cmd: lenskit data convert --amazon --item-lists ../data/Musical_Instruments.valid.csv.gz
      splits/fixed/valid/test.parquet
    deps:
      - ../data/Musical_Instruments.valid.csv.gz
    outs:
      - splits/fixed/valid/test.parquet
  import-valid-train:
    cmd: lenskit data convert --amazon ../data/Musical_Instruments.train.csv.gz splits/fixed/valid/train.dataset
    deps:
      - ../data/Musical_Instruments.train.csv.gz
    outs:
      - splits/fixed/valid/train.dataset
  run-fixed-default-als-biased:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/als-biased-default als-biased
    deps:
      - ../../../src/codex/models/als_biased.py
      - splits/fixed
    outs:
      - runs/fixed/als-biased-default
  run-fixed-default-als-implicit:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/als-implicit-default als-implicit
    deps:
      - ../../../src/codex/models/als_implicit.py
      - splits/fixed
    outs:
      - runs/fixed/als-implicit-default
  run-fixed-default-bias:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/bias-default bias
    deps:
      - ../../../src/codex/models/bias.py
      - splits/fixed
    outs:
      - runs/fixed/bias-default
  run-fixed-default-flexmf-bpr:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/flexmf-bpr-default flexmf-bpr
    deps:
      - ../../../src/codex/models/flexmf_bpr.py
      - splits/fixed
    outs:
      - runs/fixed/flexmf-bpr-default
  run-fixed-default-flexmf-explicit:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/flexmf-explicit-default flexmf-explicit
    deps:
      - ../../../src/codex/models/flexmf_explicit.py
      - splits/fixed
    outs:
      - runs/fixed/flexmf-explicit-default
  run-fixed-default-flexmf-logistic:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/flexmf-logistic-default flexmf-logistic
    deps:
      - ../../../src/codex/models/flexmf_logistic.py
      - splits/fixed
    outs:
      - runs/fixed/flexmf-logistic-default
  run-fixed-default-flexmf-warp:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/flexmf-warp-default flexmf-warp
    deps:
      - ../../../src/codex/models/flexmf_warp.py
      - splits/fixed
    outs:
      - runs/fixed/flexmf-warp-default
  run-fixed-default-popular:
    cmd: lenskit codex generate --default --ds-name=MusInst --split=splits/fixed -o
      runs/fixed/popular-default popular
    deps:
      - ../../../src/codex/models/popular.py
      - splits/fixed
    outs:
      - runs/fixed/popular-default
  run-fixed-optuna-best-als-biased:
    cmd: lenskit codex generate --param-file sweeps/fixed/als-biased-optuna.json --ds-name=MusInst
      --split=splits/fixed -o runs/fixed/als-biased-optuna-best als-biased
    deps:
      - ../../../src/codex/models/als_biased.py
      - splits/fixed
      - sweeps/fixed/als-biased-optuna.json
    outs:
      - runs/fixed/als-biased-optuna-best
  run-fixed-optuna-best-als-implicit:
    cmd: lenskit codex generate --param-file sweeps/fixed/als-implicit-optuna.json
      --ds-name=MusInst --split=splits/fixed -o runs/fixed/als-implicit-optuna-best
      als-implicit
    deps:
      - ../../../src/codex/models/als_implicit.py
      - splits/fixed
      - sweeps/fixed/als-implicit-optuna.json
    outs:
      - runs/fixed/als-implicit-optuna-best
  run-fixed-optuna-best-bias:
    cmd: lenskit codex generate --param-file sweeps/fixed/bias-optuna.json --ds-name=MusInst
      --split=splits/fixed -o runs/fixed/bias-optuna-best bias
    deps:
      - ../../../src/codex/models/bias.py
      - splits/fixed
      - sweeps/fixed/bias-optuna.json
    outs:
      - runs/fixed/bias-optuna-best
  run-fixed-optuna-best-flexmf-bpr:
    cmd: lenskit codex generate --param-file sweeps/fixed/flexmf-bpr-optuna.json --ds-name=MusInst
      --split=splits/fixed -o runs/fixed/flexmf-bpr-optuna-best flexmf-bpr
    deps:
      - ../../../src/codex/models/flexmf_bpr.py
      - splits/fixed
      - sweeps/fixed/flexmf-bpr-optuna.json
    outs:
      - runs/fixed/flexmf-bpr-optuna-best
  run-fixed-optuna-best-flexmf-explicit:
    cmd: lenskit codex generate --param-file sweeps/fixed/flexmf-explicit-optuna.json
      --ds-name=MusInst --split=splits/fixed -o runs/fixed/flexmf-explicit-optuna-best
      flexmf-explicit
    deps:
      - ../../../src/codex/models/flexmf_explicit.py
      - splits/fixed
      - sweeps/fixed/flexmf-explicit-optuna.json
    outs:
      - runs/fixed/flexmf-explicit-optuna-best
  run-fixed-optuna-best-flexmf-logistic:
    cmd: lenskit codex generate --param-file sweeps/fixed/flexmf-logistic-optuna.json
      --ds-name=MusInst --split=splits/fixed -o runs/fixed/flexmf-logistic-optuna-best
      flexmf-logistic
    deps:
      - ../../../src/codex/models/flexmf_logistic.py
      - splits/fixed
      - sweeps/fixed/flexmf-logistic-optuna.json
    outs:
      - runs/fixed/flexmf-logistic-optuna-best
  run-fixed-optuna-best-flexmf-warp:
    cmd: lenskit codex generate --param-file sweeps/fixed/flexmf-warp-optuna.json
      --ds-name=MusInst --split=splits/fixed -o runs/fixed/flexmf-warp-optuna-best
      flexmf-warp
    deps:
      - ../../../src/codex/models/flexmf_warp.py
      - splits/fixed
      - sweeps/fixed/flexmf-warp-optuna.json
    outs:
      - runs/fixed/flexmf-warp-optuna-best
  sweep-als-biased-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RMSE
      als-biased sweeps/fixed/als-biased-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/als_biased.py
    outs:
      - sweeps/fixed/als-biased-optuna
      - sweeps/fixed/als-biased-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-als-implicit-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RBP
      als-implicit sweeps/fixed/als-implicit-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/als_implicit.py
    outs:
      - sweeps/fixed/als-implicit-optuna
      - sweeps/fixed/als-implicit-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-bias-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RMSE
      bias sweeps/fixed/bias-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/bias.py
    outs:
      - sweeps/fixed/bias-optuna
      - sweeps/fixed/bias-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-flexmf-bpr-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RBP
      flexmf-bpr sweeps/fixed/flexmf-bpr-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/flexmf_bpr.py
    outs:
      - sweeps/fixed/flexmf-bpr-optuna
      - sweeps/fixed/flexmf-bpr-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-flexmf-explicit-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RMSE
      flexmf-explicit sweeps/fixed/flexmf-explicit-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/flexmf_explicit.py
    outs:
      - sweeps/fixed/flexmf-explicit-optuna
      - sweeps/fixed/flexmf-explicit-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-flexmf-logistic-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RBP
      flexmf-logistic sweeps/fixed/flexmf-logistic-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/flexmf_logistic.py
    outs:
      - sweeps/fixed/flexmf-logistic-optuna
      - sweeps/fixed/flexmf-logistic-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
  sweep-flexmf-warp-fixed-optuna:
    cmd: lenskit codex search --split=splits/fixed --test-part=valid --optuna --metric=RBP
      flexmf-warp sweeps/fixed/flexmf-warp-optuna
    deps:
      - splits/fixed
      - ../../../src/codex/models/flexmf_warp.py
    outs:
      - sweeps/fixed/flexmf-warp-optuna
      - sweeps/fixed/flexmf-warp-optuna.json:
          cache: false
    params:
      - ../../../config.toml:
          - tuning.optuna.points
