stages:
  import-ml-100k:
    cmd: python ../import-ml.py ml-100k.zip
    deps:
      - ../import-ml.py
      - ../ml-stats.sql
      - ml-100k.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: python ../../../scripts/split.py random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  Bias:
    cmd: >-
      python ../../scripts/sweep.py -p 1 Bias splits/random.duckdb
      ratings.duckdb sweeps/random/Bias.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/Bias.py
    outs:
      - sweeps/random/Bias.duckdb
  BiasedMF-ALS:
    cmd: >-
      python ../../scripts/sweep.py -p 1 BiasedMF-ALS splits/random.duckdb
      ratings.duckdb sweeps/random/BiasedMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/BiasedMF_ALS.py
    outs:
      - sweeps/random/BiasedMF-ALS.duckdb
  ImplicitMF-ALS:
    cmd: >-
      python ../../scripts/sweep.py -p 1 ImplicitMF-ALS splits/random.duckdb
      ratings.duckdb sweeps/random/ImplicitMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/ImplicitMF_ALS.py
    outs:
      - sweeps/random/ImplicitMF-ALS.duckdb
  IKNN_Explicit:
    cmd: >-
      python ../../scripts/sweep.py -p 1 IKNN_Explicit splits/random.duckdb
      ratings.duckdb sweeps/random/IKNN_Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Explicit.py
    outs:
      - sweeps/random/IKNN_Explicit.duckdb
  UKNN_Explicit:
    cmd: >-
      python ../../scripts/sweep.py -p 1 UKNN_Explicit splits/random.duckdb
      ratings.duckdb sweeps/random/UKNN_Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/UKNN_Explicit.py
    outs:
      - sweeps/random/UKNN_Explicit.duckdb
