stages:
  import-ml-100k:
    cmd: python ../import-ml.py ml-100k.zip
    deps:
      - ../import-ml.py
      - ../ml-stats.sql
      - ml-100k.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: python ../../../scripts/split.py random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
