stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/random-default/bias
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-100k.zip dataset
    deps:
      - ml-100k.zip
    outs:
      - dataset
  run-random-default-bias:
    cmd: lenskit codex generate --default --ds-name=ML100K --split=splits/random.toml
      -o runs/random-default/bias bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random-default/bias
  split-random:
    cmd: lenskit codex split random.toml
    deps:
      - random.toml
      - ../dataset
    outs:
      - random.parquet
    params:
      - ../../../config.toml:
          - random.seed
    wdir: splits
  stats:
    cmd: lenskit codex sql -D ds_name=ML100K -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
