stages:
  import-ml-100k:
    cmd: python ../import-ml.py ml-100k.zip
    deps:
    - ../import-ml.py
    - ml-100k.zip
    outs:
    - ratings.parquet
  ml-100k-stats:
    cmd: python ../../scripts/duckdb-sql.py -d stats.duckdb ../ml-stats.sql
    deps:
    - ../ml-stats.sql
    - ratings.parquet
    outs:
    - stats.duckdb
