project:
  type: website

jupyter: python3

website:
  title: "LensKit Codex"
  sidebar:
    # style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "MovieLens"
        contents:
          - href: movielens/index.qmd
            text: Overview
          - section: "ML100K"
            contents:
              - movielens/ML100K/description.qmd
          - section: "ML1M"
            contents:
              - movielens/ML1M/description.qmd
          - section: "ML10M"
            contents:
              - movielens/ML10M/description.qmd
          - section: "ML20M"
            contents:
              - movielens/ML20M/description.qmd
          - section: "ML25M"
            contents:
              - movielens/ML25M/description.qmd
      - text: GitHub
        icon: github
        href: https://github.com/lenskit/lenskit-codex

format:
  html:
    theme: cosmo
    mainfont: Alegreya Sans
    monofont: Fira Code
    css: styles.css
    toc: true
