project:
  type: website

website:
  title: "LensKit Codex"
  repo-url: https://github.com/lenskit/lenskit-codex
  repo-actions: [source, issue]
  announcement: >
    The LensKit codex is a work-in-progress and should not yet be cited or relied upon.
  sidebar:
    # style: docked
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    mainfont: Alegreya Sans
    monofont: Fira Code
    css: styles.css
    toc: true
    fig-width: 7
    fig-height: 4
    fig-dpi: 300
    fig-responsive: true
    fig-format: svg

execute:
  freeze: true
jupyter: python3
