project:
  type: website

website:
  title: "LensKit Codex"
  repo-url: https://github.com/lenskit/lenskit-codex
  repo-actions: [source, issue]
  announcement: >
    The LensKit codex is a work-in-progress and should not yet be cited or relied upon.
  page-footer:
    center: >
      Copyright © 2024 Drexel University ([license](/LICENSE.md)).  A project of the [INERTIA Laboratory](https://inertial.science) in the [College of Computing and Informatics](https://drexel.cci).  This site has not been reviewed by Drexel University, and any opinions or views expressed herein are solely those of the authors. #magic___^_^___line
  sidebar:
    # style: docked
    search: true
    contents:
      - text: Introduction
        href: index.md
      - section: Datasets
        contents:
          - auto: movielens
          - auto: amazon
      - section: Reference
        contents:
          - LICENSE.md
          - auto: eval-meta
          - auto: hardware

format:
  html:
    theme: cosmo
    mainfont: "Source Sans 3, sans-serif"
    monofont: "Source Code Pro, monospace"
    css: styles.css
    toc: true
    fig-width: 7
    fig-height: 4
    fig-dpi: 300
    fig-responsive: true
    fig-format: svg

execute:
  freeze: true
  echo: false
jupyter: python3
