project:
  type: website

jupyter: python3

website:
  title: "LensKit Codex"
  sidebar:
    # style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "MovieLens"
        contents:
        - href: movielens/index.qmd
          text: Overview
        - section: "ML25M"
          contents:
          - movielens/ML25M/description.qmd


format:
  html:
    theme: cosmo
    mainfont: Alegreya Sans
    monofont: Fira Code
    css: styles.css
    toc: true
