[random]
seed = 20240717

[tuning.optuna]
points = 40

[tuning.hyperopt]
points = 60

[tuning.random]
points = 60

[[models.include]]
model = "uknn-*"
data = "ML1*"

[[models.include]]
model = "iknn-*"
data = "ML*"

[power]
# kgCO2 / MWh - Philadelphia is in RFC East (RFCE)
co2e_rate = 269.7514

[machines.screamer]
idle_watts = 81

[machines.screamer.power_queries]
chassis = 'sum_over_time((apcupsd_nominal_power_watts{{machine="screamer"}} * (apcupsd_ups_load_percent{{machine="screamer"}} / 100))[{time}ms:1s])'
cpu = 'increase(node_rapl_package_joules_total{{machine="screamer"}}[{time}ms:1s])'
gpu = 'sum_over_time((nvidia_gpu_power_usage_milliwatts{{machine="screamer"}} / 1000)[{time}ms:1s])'

[machines.cruncher]
idle_watts = 220

[machines.cruncher.power_queries]
system = 'sum_over_time(sum(redfish_psu_input_power_watts{{machine="{machine}"}})[{elapsed}ms:1s])'
cpu = 'increase(sum(node_rapl_package_joules_total{{machine="{machine}"}})[{elapsed}ms:1s])'
gpu = 'increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{{machine="{machine}"}}[{elapsed}ms:1s]) / 1000'
