[random]
seed = 20240717

[tuning.optuna]
points = 40

[tuning.hyperopt]
points = 60

[tuning.random]
points = 60

[power]
# kgCO2 / MWh - Philadelphia is in RFC East (RFCE)
co2e_rate = 269.7514

[machines.screamer]
idle_watts = 81

[machines.cruncher]
idle_watts = 220
