stages:
  page/movielens/ML100K/als-biasedmf:
    cmd: quarto render movielens/ML100K/als-biasedmf.qmd
    deps:
      - movielens/ML100K/als-biasedmf.qmd
      - movielens/ML100K/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML100K/als-biasedmf
  page/movielens/ML100K/als-implicitmf:
    cmd: quarto render movielens/ML100K/als-implicitmf.qmd
    deps:
      - movielens/ML100K/als-implicitmf.qmd
      - movielens/ML100K/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML100K/als-implicitmf
  page/movielens/ML100K/bias:
    cmd: quarto render movielens/ML100K/bias.qmd
    deps:
      - movielens/ML100K/bias.qmd
      - movielens/ML100K/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML100K/bias
  page/movielens/ML100K/description:
    cmd: quarto render movielens/ML100K/description.qmd
    deps:
      - movielens/ML100K/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML100K/ratings.duckdb
    outs:
      - _freeze/movielens/ML100K/description
  page/movielens/ML100K/iknn-explicit:
    cmd: quarto render movielens/ML100K/iknn-explicit.qmd
    deps:
      - movielens/ML100K/iknn-explicit.qmd
      - movielens/ML100K/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML100K/iknn-explicit
  page/movielens/ML100K/iknn-implicit:
    cmd: quarto render movielens/ML100K/iknn-implicit.qmd
    deps:
      - movielens/ML100K/iknn-implicit.qmd
      - movielens/ML100K/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML100K/iknn-implicit
  page/movielens/ML10M/description:
    cmd: quarto render movielens/ML10M/description.qmd
    deps:
      - movielens/ML10M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML10M/ratings.duckdb
    outs:
      - _freeze/movielens/ML10M/description
  page/movielens/ML1M/description:
    cmd: quarto render movielens/ML1M/description.qmd
    deps:
      - movielens/ML1M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML1M/ratings.duckdb
    outs:
      - _freeze/movielens/ML1M/description
  page/movielens/ML20M/description:
    cmd: quarto render movielens/ML20M/description.qmd
    deps:
      - movielens/ML20M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML20M/ratings.duckdb
    outs:
      - _freeze/movielens/ML20M/description
  page/movielens/ML25M/description:
    cmd: quarto render movielens/ML25M/description.qmd
    deps:
      - movielens/ML25M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML25M/ratings.duckdb
    outs:
      - _freeze/movielens/ML25M/description
  page/movielens/index:
    cmd: quarto render movielens/index.qmd
    deps:
      - movielens/index.qmd
      - movielens/merged-stats.duckdb
    outs:
      - _freeze/movielens/index
