stages:
  page/movielens/ML100K/description:
    cmd: quarto render movielens/ML100K/description.qmd
    deps:
      - movielens/ML100K/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML100K/ratings.duckdb
    outs:
      - _freeze/movielens/ML100K/description
  page/movielens/ML10M/description:
    cmd: quarto render movielens/ML10M/description.qmd
    deps:
      - movielens/ML10M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML10M/ratings.duckdb
    outs:
      - _freeze/movielens/ML10M/description
  page/movielens/ML1M/description:
    cmd: quarto render movielens/ML1M/description.qmd
    deps:
      - movielens/ML1M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML1M/ratings.duckdb
    outs:
      - _freeze/movielens/ML1M/description
  page/movielens/ML20M/description:
    cmd: quarto render movielens/ML20M/description.qmd
    deps:
      - movielens/ML20M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML20M/ratings.duckdb
    outs:
      - _freeze/movielens/ML20M/description
  page/movielens/ML25M/description:
    cmd: quarto render movielens/ML25M/description.qmd
    deps:
      - movielens/ML25M/description.qmd
      - movielens/_ml_data.qmd
      - movielens/ML25M/ratings.duckdb
    outs:
      - _freeze/movielens/ML25M/description
  page/movielens/index:
    cmd: quarto render movielens/index.qmd
    deps:
      - movielens/index.qmd
      - movielens/merged-stats.duckdb
    outs:
      - _freeze/movielens/index
