stages:
  page/amazon/2023-5core/index:
    cmd: quarto render amazon/2023-5core/index.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - amazon/2023-5core/index.qmd
      - amazon/2023-5core/stats.duckdb
    outs:
      - _freeze/amazon/2023-5core/index
  page/eval-meta/attention:
    cmd: quarto render eval-meta/attention.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - eval-meta/attention.qmd
    outs:
      - _freeze/eval-meta/attention
  page/movielens/ML100K/als-biasedmf:
    cmd: quarto render movielens/ML100K/als-biasedmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/als-biasedmf.qmd
      - movielens/ML100K/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML100K/als-biasedmf
  page/movielens/ML100K/als-implicitmf:
    cmd: quarto render movielens/ML100K/als-implicitmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/als-implicitmf.qmd
      - movielens/ML100K/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML100K/als-implicitmf
  page/movielens/ML100K/bias:
    cmd: quarto render movielens/ML100K/bias.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/bias.qmd
      - movielens/ML100K/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML100K/bias
  page/movielens/ML100K/description:
    cmd: quarto render movielens/ML100K/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/description.qmd
      - movielens/ML100K/ratings.duckdb
    outs:
      - _freeze/movielens/ML100K/description
  page/movielens/ML100K/iknn-explicit:
    cmd: quarto render movielens/ML100K/iknn-explicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/iknn-explicit.qmd
      - movielens/ML100K/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML100K/iknn-explicit
  page/movielens/ML100K/iknn-implicit:
    cmd: quarto render movielens/ML100K/iknn-implicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/iknn-implicit.qmd
      - movielens/ML100K/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML100K/iknn-implicit
  page/movielens/ML100K/summary:
    cmd: quarto render movielens/ML100K/summary.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML100K/summary.qmd
      - movielens/ML100K/run-metrics.duckdb
    outs:
      - _freeze/movielens/ML100K/summary
  page/movielens/ML10M/als-biasedmf:
    cmd: quarto render movielens/ML10M/als-biasedmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/als-biasedmf.qmd
      - movielens/ML10M/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML10M/als-biasedmf
  page/movielens/ML10M/als-implicitmf:
    cmd: quarto render movielens/ML10M/als-implicitmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/als-implicitmf.qmd
      - movielens/ML10M/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML10M/als-implicitmf
  page/movielens/ML10M/bias:
    cmd: quarto render movielens/ML10M/bias.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/bias.qmd
      - movielens/ML10M/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML10M/bias
  page/movielens/ML10M/description:
    cmd: quarto render movielens/ML10M/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/description.qmd
      - movielens/ML10M/ratings.duckdb
    outs:
      - _freeze/movielens/ML10M/description
  page/movielens/ML10M/iknn-explicit:
    cmd: quarto render movielens/ML10M/iknn-explicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/iknn-explicit.qmd
      - movielens/ML10M/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML10M/iknn-explicit
  page/movielens/ML10M/iknn-implicit:
    cmd: quarto render movielens/ML10M/iknn-implicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML10M/iknn-implicit.qmd
      - movielens/ML10M/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML10M/iknn-implicit
  page/movielens/ML1M/als-biasedmf:
    cmd: quarto render movielens/ML1M/als-biasedmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/als-biasedmf.qmd
      - movielens/ML1M/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML1M/als-biasedmf
  page/movielens/ML1M/als-implicitmf:
    cmd: quarto render movielens/ML1M/als-implicitmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/als-implicitmf.qmd
      - movielens/ML1M/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML1M/als-implicitmf
  page/movielens/ML1M/bias:
    cmd: quarto render movielens/ML1M/bias.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/bias.qmd
      - movielens/ML1M/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML1M/bias
  page/movielens/ML1M/description:
    cmd: quarto render movielens/ML1M/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/description.qmd
      - movielens/ML1M/ratings.duckdb
    outs:
      - _freeze/movielens/ML1M/description
  page/movielens/ML1M/iknn-explicit:
    cmd: quarto render movielens/ML1M/iknn-explicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/iknn-explicit.qmd
      - movielens/ML1M/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML1M/iknn-explicit
  page/movielens/ML1M/iknn-implicit:
    cmd: quarto render movielens/ML1M/iknn-implicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML1M/iknn-implicit.qmd
      - movielens/ML1M/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML1M/iknn-implicit
  page/movielens/ML20M/als-biasedmf:
    cmd: quarto render movielens/ML20M/als-biasedmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/als-biasedmf.qmd
      - movielens/ML20M/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML20M/als-biasedmf
  page/movielens/ML20M/als-implicitmf:
    cmd: quarto render movielens/ML20M/als-implicitmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/als-implicitmf.qmd
      - movielens/ML20M/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML20M/als-implicitmf
  page/movielens/ML20M/bias:
    cmd: quarto render movielens/ML20M/bias.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/bias.qmd
      - movielens/ML20M/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML20M/bias
  page/movielens/ML20M/description:
    cmd: quarto render movielens/ML20M/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/description.qmd
      - movielens/ML20M/ratings.duckdb
    outs:
      - _freeze/movielens/ML20M/description
  page/movielens/ML20M/iknn-explicit:
    cmd: quarto render movielens/ML20M/iknn-explicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/iknn-explicit.qmd
      - movielens/ML20M/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML20M/iknn-explicit
  page/movielens/ML20M/iknn-implicit:
    cmd: quarto render movielens/ML20M/iknn-implicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/iknn-implicit.qmd
      - movielens/ML20M/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML20M/iknn-implicit
  page/movielens/ML20M/splitting:
    cmd: quarto render movielens/ML20M/splitting.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML20M/splitting.qmd
      - movielens/ML20M/ratings.duckdb
    outs:
      - _freeze/movielens/ML20M/splitting
  page/movielens/ML25M/als-biasedmf:
    cmd: quarto render movielens/ML25M/als-biasedmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/als-biasedmf.qmd
      - movielens/ML25M/sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML25M/als-biasedmf
  page/movielens/ML25M/als-implicitmf:
    cmd: quarto render movielens/ML25M/als-implicitmf.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/als-implicitmf.qmd
      - movielens/ML25M/sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - _freeze/movielens/ML25M/als-implicitmf
  page/movielens/ML25M/bias:
    cmd: quarto render movielens/ML25M/bias.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/bias.qmd
      - movielens/ML25M/sweeps/random/Bias.duckdb
    outs:
      - _freeze/movielens/ML25M/bias
  page/movielens/ML25M/description:
    cmd: quarto render movielens/ML25M/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/description.qmd
      - movielens/ML25M/ratings.duckdb
    outs:
      - _freeze/movielens/ML25M/description
  page/movielens/ML25M/iknn-explicit:
    cmd: quarto render movielens/ML25M/iknn-explicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/iknn-explicit.qmd
      - movielens/ML25M/sweeps/random/IKNN-Explicit.duckdb
    outs:
      - _freeze/movielens/ML25M/iknn-explicit
  page/movielens/ML25M/iknn-implicit:
    cmd: quarto render movielens/ML25M/iknn-implicit.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/iknn-implicit.qmd
      - movielens/ML25M/sweeps/random/IKNN-Implicit.duckdb
    outs:
      - _freeze/movielens/ML25M/iknn-implicit
  page/movielens/ML25M/splitting:
    cmd: quarto render movielens/ML25M/splitting.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML25M/splitting.qmd
      - movielens/ML25M/ratings.duckdb
    outs:
      - _freeze/movielens/ML25M/splitting
  page/movielens/ML32M/description:
    cmd: quarto render movielens/ML32M/description.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML32M/description.qmd
      - movielens/ML32M/ratings.duckdb
    outs:
      - _freeze/movielens/ML32M/description
  page/movielens/ML32M/splitting:
    cmd: quarto render movielens/ML32M/splitting.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/ML32M/splitting.qmd
      - movielens/ML32M/ratings.duckdb
    outs:
      - _freeze/movielens/ML32M/splitting
  page/movielens/index:
    cmd: quarto render movielens/index.qmd --profile prerender
    deps:
      - _quarto-prerender.yml
      - _quarto.yml
      - movielens/index.qmd
      - movielens/merged-stats.duckdb
    outs:
      - _freeze/movielens/index
