name: lk-codex
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas=2
  - duckdb-cli>=1.0,<2
  - python-duckdb>=1.0,<2
  - pyarrow>=16
  - humanize=4
  - si-prefix=1.2
  - tabulate>=0.9
  - quarto>=1.4
  - deno
  - plotnine=0.13
  - matplotlib>=3.6
  - ipython>=8
  - notebook>=7
  - jupyterlab
  - jupyter-cache
  - dvc
  - dvc-s3
  - dvc-webdav
  - dvc-ssh
  - libblas=*=*mkl* # [linux]
  - pytorch-mutex=*=cuda # [linux]
  - ruff
  - just
  - pip:
      - sandal>=0.1.0a5
      - progress-api>=0.1.0a1
      - docopt-ng>=0.9
platforms:
  - linux-64
  - osx-arm64
