dependencies:
  - pip
  - pandas >=1.5,<3
  - numpy >=1.23
  - scipy >=1.9.0
  - pytorch >=2.1,<3
  - threadpoolctl >=3.0
  - pip:
      - seedbank>=0.2.0a2
      - progress-api>=0.1.0a9
      - manylog>=0.1.0a5
