[workspace]
authors = ["Michael Ekstrand <mdekstrand@drexel.edu>"]
channels = ["conda-forge"]
name = "lenskit-codex"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "~=3.14.0"
tk = ">=8.6.13"
"ruamel.yaml" = "~=0.18.10"
humanize = "~=4.0"
deepmerge = "~=2.1"
glom = "~=24.11"
pandas = "~=2.1"
python-duckdb = "~=1.5"
duckdb-cli = "~=1.5"
pyarrow = ">=20.0"
statsmodels = ">=0.14"
zstandard = ">=0.23"
plotnine = "~=0.15.0"
matplotlib = "~=3.6"
seaborn = "~=0.13.2"
itables = "~=2.2"
tabulate = ">=0.9"
notebook = ">=7"
dvc = "~=3.50"
dvc-webdav = "~=3.0"
dvc-s3 = "~=3.0"
docopt-ng = ">=0.9.0"
quarto = "~=1.9.0"
jimtcl = ">=0.83,<0.84"

[pypi-dependencies]
lenskit-codex = { path = ".", editable = true }

[target.linux-64.dependencies]
nomkl = "*"

[feature.run.dependencies]
lenskit = "~=2026.2"
pytorch = "~=2.10"
ray-tune = "~=2.45"
optuna = "~=4.0"
hyperopt = "~=0.2.7"
numpy = "~=2.0"

[feature.run.system-requirements]
cuda = "13"

[feature.dev.dependencies]
dprint = ">=0.50"
py-spy = ">=0.4"
ruff = ">=0.4"
ipython = ">=8"
parquet-tools = ">=0.2.16"
pre-commit = ">=0.4.0"
visidata = ">=3.1.1"

[feature.run.target.linux-64.dependencies]
pytorch-gpu = "*"

[environments]
default = ["run", "dev"]
site = []
