[project]
name = "lenskit-codex"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

# core dependencies to analyze the data & generate site
[dependencies]
python = "~=3.11.0"
pandas = "~=2.1"
pydantic = ">=2.8,<3"
duckdb-cli = "~=1.0"
python-duckdb = "~=1.0"
pyarrow = ">=16"
humanize = "~=4.0"
si-prefix = "~=1.2"
tabulate = ">=0.9"
quarto = "~=1.4"
plotnine = "~=0.13.0"
matplotlib = "~=3.6"
ipython = ">=8"
notebook = ">=7"
jupyter-cache = "*"
dvc = "~=3.50"
dvc-s3 = "*"
dvc-webdav = "*"
dvc-ssh = "*"

[pypi-dependencies]
sandal = { git = "https://github.com/mdekstrand/sandal" }
progress-api = { git = "https://github.com/lenskit/progress-api" }
docopt-ng = ">=0.9"

# dependencies to run the recommender algorithms
[feature.run.dependencies]
pytorch = "~=2.1"
lenskit = "~=0.14.4"

# dependencies for running with CUDA
[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }

[feature.cuda.dependencies]
pytorch-gpu = ">=2"

# dependencies for dev work on the codex
[feature.dev.dependencies]
deno = "~=1.30"
ruff = "*"
just = "*"
pre-commit = "~=3.7"
jupyterlab = "*"

[target.linux.dependencies]
libblas = { build = "*mkl*" }

[environments]
default = { features = ["run"], solve-group = "main" }
publish = { solve-group = "main" }
dev = { features = ["dev"], solve-group = "main" }
cuda = { features = ["run", "cuda"], solve-group = "cuda" }
cuda-dev = { features = ["run", "cuda", "dev"], solve-group = "cuda" }
