[project]
name = "lenskit-codex"
channels = ["https://prefix.dev/lenskit-dev", "conda-forge"]
platforms = ["linux-64", "osx-arm64"]

# core dependencies to work with the data and website
[dependencies]
python = "~=3.12.0"

click = "~=8.0"
invoke = "~=2.2"

pydantic = ">=2.8,<3"
pyyaml = "~=6.0"
humanize = "~=4.0"
deepmerge = ">=2.0,<3"
tabulate = ">=0.9"
requests = ">=2.32.3,<3"

statsmodels = "~=0.14.4"
distfit = "~=1.8"
plotnine = "~=0.14.0"
matplotlib-base = "~=3.6"
seaborn-base = "~=0.13.2"
notebook = ">=7"
itables = "~=2.2"
jupyter-cache = "*"

dvc = "~=3.50"
dvc-webdav = "*"
dvc-s3 = "*"
dvc-azure = "*"

quarto = "~=1.6"
# pandoc = "==3.2.0"
tectonic = ">=0.15.0,<0.16"

[pypi-dependencies]
lenskit-codex = { path = ".", editable = true }

# exclude MKL for smaller environments in some cases
[feature.nomkl.dependencies]
nomkl = "*"

# dependencies to analyze recommender outputs
[feature.analyze.dependencies]
pandas = "~=2.1"
duckdb-cli = "~=1.0"
python-duckdb = "~=1.0"
pyarrow = ">=16"

# dependencies to run the recommender algorithms
[feature.run.dependencies]
pytorch = "~=2.1"
numpy = "~=2.0"
pandas = "~=2.0"
scipy = "~=1.10"
numba = "~=0.56"
ray-default = "~=2.42"
ray-tune = "~=2.42"
optuna = "~=4.2"
hyperopt = "~=0.2.7"
# hpfrec = "~=0.2.13"
# implicit = "~=0.7.0"
rust = "~=1.84"
lenskit = ">2025.3.0a2,<2026"
lenskit-implicit = "~=2025.3.0a2"

[feature.run.system-requirements]
cuda = "11"

[feature.run.pypi-dependencies]
# lenskit = { version = "~=2025.2", extras = ["implicit", "sklearn", "funksvd"] }
# lenskit = { git = "https://github.com/lenskit/lkpy.git" }
# lenskit = { git = "https://github.com/mdekstrand/lkpy.git", branch = "feature/als-trainer-checkpoint" }
# lenskit = { path = "../lkpy", editable = true }

[feature.run.target.linux.dependencies]
pytorch-gpu = ">=2"

[feature.run.target.linux-64.dependencies]
libblas = { build = "*mkl*" }

# dependencies for dev work on the codex
[feature.dev.dependencies]
jsonnet = "~=0.20.0"
dprint = ">=0.49"
line_profiler = "~=4.1"
ruff = "*"
pre-commit = "~=3.7"
ipython = ">=8"
jupyterlab = "*"
parquet-tools = ">=0.2.16,<0.3"

[environments]
default = { features = ["run", "analyze"], solve-group = "main" }
publish = { features = ["nomkl"] }
dev = { features = ["run", "analyze", "dev"], solve-group = "main" }
