[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "lenskit-codex"
description = "Repository of LensKit runs and evaluation outputs."
dynamic = ["version"]

[[project.authors]]
name = "Michael Ekstrand"
email = "mdekstrand@drexel.edu"

[tool.setuptools.packages.find]
include = ["lenskit/*"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".git", "__pycache__", "build", "dist", "*/tests/*", ".pixi/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.pyright]
exclude = [".pixi/*"]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
