[build-system]
requires = ["hatchling ~=1.0"]
build-backend = "hatchling.build"

[project]
name = "lenskit-codex"
version = "0.1.0"
description = "LensKit run results"
authors = [{ name = "Michael Ekstrand", email = "mdekstrand@drexel.edu" }]
requires-python = "==3.12.*"
dependencies = [
  "click ~=8.0",
  "invoke ~=2.2",

  "pydantic >=2.8,<3",
  "pyyaml ~=6.0",
  "humanize ~=4.0",
  "deepmerge >=2.0,<3",
  "glom ~=24.11",
  "requests >=2.32.3,<3",

  "pandas ~=2.1",
  "duckdb ~=1.2",
  "pyarrow >=16",
  "statsmodels ~=0.14.4",
  "distfit ~=1.8",
  "zstandard >=0.23",

  "plotnine ~=0.14.0",
  "matplotlib ~=3.6",
  "seaborn ~=0.13.2",
  "itables ~=2.2",
  "tabulate >=0.9",

  "notebook >=7",
  "jupyter-cache",

  "dvc ~=3.50",
  "quarto-cli ~=1.7",
]

[dependency-groups]
run = [
  "ray[tune] ~= 2.45",
  "numpy ~=2.0",
  "lenskit @ https://github.com/lenskit/lkpy.git",
]
cpu = ["torch ~=2.6"]
cuda = ["torch ~=2.6"]
dev = [
  "jsonnet ~=0.20.0",
  "jinja2 ~=3.1",
  "line_profiler ~=4.1",
  "ruff >=0.4",
  "ipython >=8",
  "jupyterlab >=3",
  "parquet-tools ~=0.2.16",
  { include-group = "run" },
]

[tool.uv]
conflicts = [[{ group = "cpu" }, { group = "cuda" }]]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", group = "cpu" },
  { index = "pytorch-cuda", group = "cuda" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[project.entry-points."lenskit.cli.plugins"]
lenskit-codex = "codex.tools:codex"

[tool.hatch.build.targets.wheel]
packages = ["src/codex"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".git", "__pycache__", "build", "dist", "*/tests/*", ".pixi/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["F403", "F405"]

[tool.pyright]
exclude = [".pixi/*"]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
