[build-system]
requires = ["hatchling ~=1.0"]
build-backend = "hatchling.build"

[project]
name = "lenskit-codex"
version = "0.1.0"
description = "LensKit run results"
authors = [{ name = "Michael Ekstrand", email = "mdekstrand@drexel.edu" }]
requires-python = ">=3.12"
dependencies = [
  "invoke ~=2.2",
  "dvc[webdav] ~=3.50",

  "pandas ~=2.1",
  "duckdb ~=1.0",
  "pyarrow >=16",
  "zstandard",

  "pydantic ~=2.8",
  "requests ~=2.32",
  "deepmerge ~=2.0",

  "statsmodels ~=0.14.4",
  "distfit ~=1.8",

  "plotnine ~=0.14.0",
  "matplotlib ~=3.6",
  "seaborn ~=0.13.2",
  "tabulate >=0.9",
  "itables ~=2.2",

  "notebook >=7",
]

[dependency-groups]
run = [
  "lenskit @ git+https://github.com/lenskit/lkpy.git",
  "ray[default] ~=2.42",
  "torch ~=2.5",
]
dev = [
  { include-group = "run" },
  "jsonnet ~=0.20.0",
  "line_profiler ~=4.1",
  "ruff",
  "ipython",
  "pre-commit ~=4.2",
  "parquet-tools",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-gpu", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[project.entry-points."lenskit.cli.plugins"]
lenskit-codex = "codex.tools:codex"

[tool.hatch.build.targets.wheel]
packages = ["src/codex"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".git", "__pycache__", "build", "dist", "*/tests/*", ".pixi/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.pyright]
exclude = [".pixi/*"]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
