[build-system]
requires = ["hatchling ~=1.0"]
build-backend = "hatchling.build"

[project]
name = "lenskit-codex"
version = "0.1.0"
description = "LensKit run results"
authors = [{ name = "Michael Ekstrand", email = "mdekstrand@drexel.edu" }]

[project.scripts]
lenskit-codex = "codex.tools:codex"

[tool.hatch.build.targets.wheel]
packages = ["src/codex"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".git", "__pycache__", "build", "dist", "*/tests/*", ".pixi/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.pyright]
exclude = [".pixi/*"]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
