[meta]
name = "flexmf-warp"

[options]
base = "std:topn"

[components.scorer]
class = "lenskit.flexmf.FlexMFImplicitScorer"

[components.scorer.config]
epochs = 5
loss = "warp"
reg_method = "AdamW"
user_bias = false
item_bias = false
