[search]
metric = "RBP"
max_epochs = 50
num_gpus = 0.2

[space.scorer]
embedding_size_exp = { type = "int", min = 3, max = 10, scale = "log" }
regularization = { type = "float", min = 1e-4, max = 10, scale = "log" }
learning_rate = { type = "float", min = 1e-3, max = 0.1, scale = "log" }
# negative_count = { type = "int", min = 1, max = 5 }
positive_weight = { type = "int", min = 1, max = 10 }
item_bias = { type = "bool" }

[pipeline]
file = "pipeline.toml"
