stages:
  import-ml-1m:
    cmd: python ../import-ml.py ml-1m.zip
    deps:
    - ../import-ml.py
    - ../../codex/rating_stat_views.sql
    - ml-1m.zip
    outs:
    - ratings.duckdb
    - ratings.parquet
