stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-1m.zip
    deps:
      - ../ml-stats.sql
      - ml-1m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: lenskit-codex split random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  sweep-random-Bias:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML1M --split=splits/random.toml --test-part=0 Bias sweeps/random/Bias
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/random/Bias
  export-random-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/Bias.json sweeps/random/Bias RMSE
    deps:
      - sweeps/random/Bias
    outs:
      - sweeps/random/Bias.json:
          cache: false
  sweep-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML1M --split=splits/random.toml --test-part=0 BiasedMF-ALS sweeps/random/BiasedMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/random/BiasedMF-ALS
  export-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/BiasedMF-ALS.json sweeps/random/BiasedMF-ALS RMSE
    deps:
      - sweeps/random/BiasedMF-ALS
    outs:
      - sweeps/random/BiasedMF-ALS.json:
          cache: false
  sweep-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Explicit sweeps/random/IKNN-Explicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/random/IKNN-Explicit
  export-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Explicit.json sweeps/random/IKNN-Explicit RMSE
    deps:
      - sweeps/random/IKNN-Explicit
    outs:
      - sweeps/random/IKNN-Explicit.json:
          cache: false
  sweep-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Implicit sweeps/random/IKNN-Implicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/random/IKNN-Implicit
  export-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Implicit.json sweeps/random/IKNN-Implicit RBP
    deps:
      - sweeps/random/IKNN-Implicit
    outs:
      - sweeps/random/IKNN-Implicit.json:
          cache: false
  sweep-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML1M --split=splits/random.toml --test-part=0 ImplicitMF-ALS sweeps/random/ImplicitMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/random/ImplicitMF-ALS
  export-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/ImplicitMF-ALS.json sweeps/random/ImplicitMF-ALS RBP
    deps:
      - sweeps/random/ImplicitMF-ALS
    outs:
      - sweeps/random/ImplicitMF-ALS.json:
          cache: false
  run-random-default-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Bias.json --test-part=-0 --split=splits/random.toml -o runs/random-sweep-best/Bias Bias
    outs:
      - runs/random-sweep-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias.json
  run-random-default-Popular:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml -o runs/random-default/Popular Popular
    outs:
      - runs/random-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/BiasedMF-ALS.json --test-part=-0 --split=splits/random.toml -o runs/random-sweep-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/random-sweep-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/BiasedMF-ALS.json
  run-random-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Explicit.json --test-part=-0 --split=splits/random.toml -o runs/random-sweep-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-sweep-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Explicit.json
  run-random-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Implicit.json --test-part=-0 --split=splits/random.toml -o runs/random-sweep-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-sweep-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Implicit.json
  run-random-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/ImplicitMF-ALS.json --test-part=-0 --split=splits/random.toml -o runs/random-sweep-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/random-sweep-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/ImplicitMF-ALS.json
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics run-metrics.duckdb --view-script=../ml-run-metrics.sql runs
    deps: []
    outs:
      - run-metrics.duckdb
