stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-1m.zip
    deps:
      - ../ml-stats.sql
      - ml-1m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: lenskit-codex split random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  sweep-random-grid-Bias:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML1M --split=splits/random.toml --test-part=0 Bias sweeps/random/Bias-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/random/Bias-grid
  export-random-grid-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/Bias-grid.json sweeps/random/Bias-grid RMSE
    deps:
      - sweeps/random/Bias-grid
    outs:
      - sweeps/random/Bias-grid.json:
          cache: false
  sweep-random-random-Bias:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML1M --split=splits/random.toml --test-part=0 Bias sweeps/random/Bias-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/random/Bias-random
  export-random-random-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/Bias-random.json sweeps/random/Bias-random RMSE
    deps:
      - sweeps/random/Bias-random
    outs:
      - sweeps/random/Bias-random.json:
          cache: false
  sweep-random-grid-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML1M --split=splits/random.toml --test-part=0 BiasedMF-ALS sweeps/random/BiasedMF-ALS-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/random/BiasedMF-ALS-grid
  export-random-grid-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/BiasedMF-ALS-grid.json sweeps/random/BiasedMF-ALS-grid RMSE
    deps:
      - sweeps/random/BiasedMF-ALS-grid
    outs:
      - sweeps/random/BiasedMF-ALS-grid.json:
          cache: false
  sweep-random-grid-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Explicit sweeps/random/IKNN-Explicit-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/random/IKNN-Explicit-grid
  export-random-grid-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Explicit-grid.json sweeps/random/IKNN-Explicit-grid RMSE
    deps:
      - sweeps/random/IKNN-Explicit-grid
    outs:
      - sweeps/random/IKNN-Explicit-grid.json:
          cache: false
  sweep-random-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Explicit sweeps/random/IKNN-Explicit-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/random/IKNN-Explicit-random
  export-random-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Explicit-random.json sweeps/random/IKNN-Explicit-random RMSE
    deps:
      - sweeps/random/IKNN-Explicit-random
    outs:
      - sweeps/random/IKNN-Explicit-random.json:
          cache: false
  sweep-random-grid-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Implicit sweeps/random/IKNN-Implicit-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/random/IKNN-Implicit-grid
  export-random-grid-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Implicit-grid.json sweeps/random/IKNN-Implicit-grid RBP
    deps:
      - sweeps/random/IKNN-Implicit-grid
    outs:
      - sweeps/random/IKNN-Implicit-grid.json:
          cache: false
  sweep-random-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML1M --split=splits/random.toml --test-part=0 IKNN-Implicit sweeps/random/IKNN-Implicit-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/random/IKNN-Implicit-random
  export-random-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Implicit-random.json sweeps/random/IKNN-Implicit-random RBP
    deps:
      - sweeps/random/IKNN-Implicit-random
    outs:
      - sweeps/random/IKNN-Implicit-random.json:
          cache: false
  sweep-random-grid-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML1M --split=splits/random.toml --test-part=0 ImplicitMF-ALS sweeps/random/ImplicitMF-ALS-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/random/ImplicitMF-ALS-grid
  export-random-grid-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/ImplicitMF-ALS-grid.json sweeps/random/ImplicitMF-ALS-grid RBP
    deps:
      - sweeps/random/ImplicitMF-ALS-grid
    outs:
      - sweeps/random/ImplicitMF-ALS-grid.json:
          cache: false
  run-random-default-Bias:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/Bias Bias
    outs:
      - runs/random-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-grid-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Bias-grid.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-grid-best/Bias Bias
    outs:
      - runs/random-grid-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias-grid.json
  run-random-random-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Bias-random.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-random-best/Bias Bias
    outs:
      - runs/random-random-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias-random.json
  run-random-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/random-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-grid-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/BiasedMF-ALS-grid.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-grid-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/random-grid-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/BiasedMF-ALS-grid.json
  run-random-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-grid-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Explicit-grid.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-grid-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-grid-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Explicit-grid.json
  run-random-random-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Explicit-random.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-random-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-random-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Explicit-random.json
  run-random-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-grid-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Implicit-grid.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-grid-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-grid-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Implicit-grid.json
  run-random-random-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Implicit-random.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-random-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-random-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Implicit-random.json
  run-random-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/random-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-grid-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/ImplicitMF-ALS-grid.json --test-part=-0 --ds-name=ML1M --split=splits/random.toml -o runs/random-grid-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/random-grid-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/ImplicitMF-ALS-grid.json
  run-random-default-Popular:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML1M --split=splits/random.toml -o runs/random-default/Popular Popular
    outs:
      - runs/random-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/random.duckdb
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics -S run-summary.csv -U run-user-metrics.parquet -L runs/manifest.csv
    deps:
      - runs/random-default/Bias
      - runs/random-grid-best/Bias
      - runs/random-random-best/Bias
      - runs/random-default/BiasedMF-ALS
      - runs/random-grid-best/BiasedMF-ALS
      - runs/random-default/IKNN-Explicit
      - runs/random-grid-best/IKNN-Explicit
      - runs/random-random-best/IKNN-Explicit
      - runs/random-default/IKNN-Implicit
      - runs/random-grid-best/IKNN-Implicit
      - runs/random-random-best/IKNN-Implicit
      - runs/random-default/ImplicitMF-ALS
      - runs/random-grid-best/ImplicitMF-ALS
      - runs/random-default/Popular
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
