stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/random/als-biased-default
      - runs/random/als-implicit-default
      - runs/random/bias-default
      - runs/random/flexmf-explicit-default
      - runs/random/iknn-explicit-default
      - runs/random/iknn-implicit-default
      - runs/random/implicit-bpr-default
      - runs/random/popular-default
      - runs/random/uknn-explicit-default
      - runs/random/uknn-implicit-default
      - runs/random/als-biased-random-best
      - runs/random/als-implicit-random-best
      - runs/random/bias-random-best
      - runs/random/flexmf-explicit-random-best
      - runs/random/iknn-explicit-random-best
      - runs/random/iknn-implicit-random-best
      - runs/random/implicit-bpr-random-best
      - runs/random/uknn-explicit-random-best
      - runs/random/uknn-implicit-random-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-1m.zip dataset
    deps:
      - ml-1m.zip
    outs:
      - dataset
  run-random-default-als-biased:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/als-biased-default als-biased
    deps:
      - ../../src/codex/models/als_biased.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/als-biased-default
  run-random-default-als-implicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/als-implicit-default als-implicit
    deps:
      - ../../src/codex/models/als_implicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/als-implicit-default
  run-random-default-bias:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/bias-default bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/bias-default
  run-random-default-flexmf-explicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/flexmf-explicit-default flexmf-explicit
    deps:
      - ../../src/codex/models/flexmf_explicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/flexmf-explicit-default
  run-random-default-iknn-explicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/iknn-explicit-default iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/iknn-explicit-default
  run-random-default-iknn-implicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/iknn-implicit-default iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/iknn-implicit-default
  run-random-default-implicit-bpr:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/implicit-bpr-default implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/implicit-bpr-default
  run-random-default-popular:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/popular-default popular
    deps:
      - ../../src/codex/models/popular.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/popular-default
  run-random-default-uknn-explicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/uknn-explicit-default uknn-explicit
    deps:
      - ../../src/codex/models/uknn_explicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/uknn-explicit-default
  run-random-default-uknn-implicit:
    cmd: lenskit codex generate --default --ds-name=ML1M --split=splits/random.toml
      -o runs/random/uknn-implicit-default uknn-implicit
    deps:
      - ../../src/codex/models/uknn_implicit.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/uknn-implicit-default
  run-random-random-best-als-biased:
    cmd: lenskit codex generate --param-file sweeps/random/als-biased-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/als-biased-random-best
      als-biased
    deps:
      - ../../src/codex/models/als_biased.py
      - dataset
      - splits/random.parquet
      - sweeps/random/als-biased-random.json
    outs:
      - runs/random/als-biased-random-best
  run-random-random-best-als-implicit:
    cmd: lenskit codex generate --param-file sweeps/random/als-implicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/als-implicit-random-best
      als-implicit
    deps:
      - ../../src/codex/models/als_implicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/als-implicit-random.json
    outs:
      - runs/random/als-implicit-random-best
  run-random-random-best-bias:
    cmd: lenskit codex generate --param-file sweeps/random/bias-random.json --ds-name=ML1M
      --split=splits/random.toml -o runs/random/bias-random-best bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/random.parquet
      - sweeps/random/bias-random.json
    outs:
      - runs/random/bias-random-best
  run-random-random-best-flexmf-explicit:
    cmd: lenskit codex generate --param-file sweeps/random/flexmf-explicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/flexmf-explicit-random-best
      flexmf-explicit
    deps:
      - ../../src/codex/models/flexmf_explicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/flexmf-explicit-random.json
    outs:
      - runs/random/flexmf-explicit-random-best
  run-random-random-best-iknn-explicit:
    cmd: lenskit codex generate --param-file sweeps/random/iknn-explicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/iknn-explicit-random-best
      iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/iknn-explicit-random.json
    outs:
      - runs/random/iknn-explicit-random-best
  run-random-random-best-iknn-implicit:
    cmd: lenskit codex generate --param-file sweeps/random/iknn-implicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/iknn-implicit-random-best
      iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/iknn-implicit-random.json
    outs:
      - runs/random/iknn-implicit-random-best
  run-random-random-best-implicit-bpr:
    cmd: lenskit codex generate --param-file sweeps/random/implicit-bpr-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/implicit-bpr-random-best
      implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/random.parquet
      - sweeps/random/implicit-bpr-random.json
    outs:
      - runs/random/implicit-bpr-random-best
  run-random-random-best-uknn-explicit:
    cmd: lenskit codex generate --param-file sweeps/random/uknn-explicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/uknn-explicit-random-best
      uknn-explicit
    deps:
      - ../../src/codex/models/uknn_explicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/uknn-explicit-random.json
    outs:
      - runs/random/uknn-explicit-random-best
  run-random-random-best-uknn-implicit:
    cmd: lenskit codex generate --param-file sweeps/random/uknn-implicit-random.json
      --ds-name=ML1M --split=splits/random.toml -o runs/random/uknn-implicit-random-best
      uknn-implicit
    deps:
      - ../../src/codex/models/uknn_implicit.py
      - dataset
      - splits/random.parquet
      - sweeps/random/uknn-implicit-random.json
    outs:
      - runs/random/uknn-implicit-random-best
  split-random:
    cmd: lenskit codex split random.toml
    deps:
      - random.toml
      - ../dataset
    outs:
      - random.parquet
    params:
      - ../../../config.toml:
          - random.seed
    wdir: splits
  stats:
    cmd: lenskit codex sql -D ds_name=ML1M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
  sweep-als-biased-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RMSE
      als-biased sweeps/random/als-biased-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/als_biased.py
    outs:
      - sweeps/random/als-biased-random
      - sweeps/random/als-biased-random.json:
          cache: false
  sweep-als-implicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RBP
      als-implicit sweeps/random/als-implicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/als_implicit.py
    outs:
      - sweeps/random/als-implicit-random
      - sweeps/random/als-implicit-random.json:
          cache: false
  sweep-bias-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RMSE
      bias sweeps/random/bias-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/bias.py
    outs:
      - sweeps/random/bias-random
      - sweeps/random/bias-random.json:
          cache: false
  sweep-flexmf-explicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RMSE
      flexmf-explicit sweeps/random/flexmf-explicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/flexmf_explicit.py
    outs:
      - sweeps/random/flexmf-explicit-random
      - sweeps/random/flexmf-explicit-random.json:
          cache: false
  sweep-iknn-explicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RMSE
      iknn-explicit sweeps/random/iknn-explicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/iknn_explicit.py
    outs:
      - sweeps/random/iknn-explicit-random
      - sweeps/random/iknn-explicit-random.json:
          cache: false
  sweep-iknn-implicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RBP
      iknn-implicit sweeps/random/iknn-implicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/iknn_implicit.py
    outs:
      - sweeps/random/iknn-implicit-random
      - sweeps/random/iknn-implicit-random.json:
          cache: false
  sweep-implicit-bpr-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RBP
      implicit-bpr sweeps/random/implicit-bpr-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/implicit_bpr.py
    outs:
      - sweeps/random/implicit-bpr-random
      - sweeps/random/implicit-bpr-random.json:
          cache: false
  sweep-uknn-explicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --sample-count=60
      --random --metric=RMSE uknn-explicit sweeps/random/uknn-explicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/uknn_explicit.py
    outs:
      - sweeps/random/uknn-explicit-random
      - sweeps/random/uknn-explicit-random.json:
          cache: false
  sweep-uknn-implicit-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --sample-count=60
      --random --metric=RBP uknn-implicit sweeps/random/uknn-implicit-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/uknn_implicit.py
    outs:
      - sweeps/random/uknn-implicit-random
      - sweeps/random/uknn-implicit-random.json:
          cache: false
