stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/random/bias-default
      - runs/random/bias-random-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-1m.zip dataset
    deps:
      - ml-1m.zip
    outs:
      - dataset
  run-random-default-bias:
    cmd: lenskit codex generate --default --ds-name=../.. --split=splits/random.toml
      -o runs/random/bias-default bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/random.parquet
    outs:
      - runs/random/bias-default
  run-random-random-best-bias:
    cmd: lenskit codex generate --param-file sweeps/random/bias-random.json --ds-name=../..
      --split=splits/random.toml -o runs/random/bias-random-best bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/random.parquet
      - sweeps/random/bias-random.json
    outs:
      - runs/random/bias-random-best
  split-random:
    cmd: lenskit codex split random.toml
    deps:
      - random.toml
      - ../dataset
    outs:
      - random.parquet
    params:
      - ../../../config.toml:
          - random.seed
    wdir: splits
  stats:
    cmd: lenskit codex sql -D ds_name=ML1M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
  sweep-bias-random-random:
    cmd: lenskit codex search --split=splits/random.toml --test-part=0 --random --metric=RMSE
      bias sweeps/random/bias-random
    deps:
      - splits/random.parquet
      - ../../src/codex/models/bias.py
    outs:
      - sweeps/random/bias-random
      - sweeps/random/bias-random.json:
          cache: false
