stages:
  import:
    cmd: python ../import-ml.py ml-1m.zip
    deps:
      - ../import-ml.py
      - ../ml-stats.sql
      - ml-1m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: python ../../../action.py split random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  sweep-random-Bias:
    cmd: >-
      python ../../action.py sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb Bias sweeps/random/Bias.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/Bias.py
    outs:
      - sweeps/random/Bias.duckdb
  export-random-Bias:
    cmd: python ../../action.py sweep export sweeps/random/Bias.duckdb rmse
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/Bias.duckdb
    outs:
      - sweeps/random/Bias.csv
      - sweeps/random/Bias.json:
          cache: false
  sweep-random-BiasedMF-ALS:
    cmd: >-
      python ../../action.py sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb BiasedMF-ALS sweeps/random/BiasedMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/BiasedMF_ALS.py
    outs:
      - sweeps/random/BiasedMF-ALS.duckdb
  export-random-BiasedMF-ALS:
    cmd: python ../../action.py sweep export sweeps/random/BiasedMF-ALS.duckdb rmse
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - sweeps/random/BiasedMF-ALS.csv
      - sweeps/random/BiasedMF-ALS.json:
          cache: false
  sweep-random-ImplicitMF-ALS:
    cmd: >-
      python ../../action.py sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb ImplicitMF-ALS sweeps/random/ImplicitMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/ImplicitMF_ALS.py
    outs:
      - sweeps/random/ImplicitMF-ALS.duckdb
  export-random-ImplicitMF-ALS:
    cmd: >-
      python ../../action.py sweep export sweeps/random/ImplicitMF-ALS.duckdb ndcg
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - sweeps/random/ImplicitMF-ALS.csv
      - sweeps/random/ImplicitMF-ALS.json:
          cache: false
  sweep-random-IKNN-Explicit:
    cmd: >-
      python ../../action.py sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb IKNN-Explicit sweeps/random/IKNN-Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Explicit.py
    outs:
      - sweeps/random/IKNN-Explicit.duckdb
  export-random-IKNN-Explicit:
    cmd: >-
      python ../../action.py sweep export sweeps/random/IKNN-Explicit.duckdb rmse
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/IKNN-Explicit.duckdb
    outs:
      - sweeps/random/IKNN-Explicit.csv
      - sweeps/random/IKNN-Explicit.json:
          cache: false
  sweep-random-IKNN-Implicit:
    cmd: >-
      python ../../action.py sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb IKNN-Implicit sweeps/random/IKNN-Implicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Implicit.py
    outs:
      - sweeps/random/IKNN-Implicit.duckdb
  export-random-IKNN-Implicit:
    cmd: >-
      python ../../action.py sweep export sweeps/random/IKNN-Implicit.duckdb ndcg
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/IKNN-Implicit.duckdb
    outs:
      - sweeps/random/IKNN-Implicit.csv
      - sweeps/random/IKNN-Implicit.json:
          cache: false
  run-random-default-Bias:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/Bias.json --recommendations=runs/random-default/Bias-recs.parquet --predictions=runs/random-default/Bias-preds.parquet Bias
    outs:
      - runs/random-default/Bias.json
      - runs/random-default/Bias-recs.parquet
      - runs/random-default/Bias-preds.parquet
    deps:
      - ../../codex/models/Bias.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-Bias:
    cmd: >-
      python ../../action.py generate --param-file=sweeps/random/Bias.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-sweep-best/Bias.json --recommendations=runs/random-sweep-best/Bias-recs.parquet --predictions=runs/random-sweep-best/Bias-preds.parquet Bias
    outs:
      - runs/random-sweep-best/Bias.json
      - runs/random-sweep-best/Bias-recs.parquet
      - runs/random-sweep-best/Bias-preds.parquet
    deps:
      - ../../codex/models/Bias.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias.json
  run-random-default-Popular:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/Popular.json --recommendations=runs/random-default/Popular-recs.parquet Popular
    outs:
      - runs/random-default/Popular.json
      - runs/random-default/Popular-recs.parquet
    deps:
      - ../../codex/models/Popular.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-default-BiasedMF-ALS:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/BiasedMF-ALS.json --recommendations=runs/random-default/BiasedMF-ALS-recs.parquet --predictions=runs/random-default/BiasedMF-ALS-preds.parquet BiasedMF-ALS
    outs:
      - runs/random-default/BiasedMF-ALS.json
      - runs/random-default/BiasedMF-ALS-recs.parquet
      - runs/random-default/BiasedMF-ALS-preds.parquet
    deps:
      - ../../codex/models/BiasedMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-BiasedMF-ALS:
    cmd: >-
      python ../../action.py generate --param-file=sweeps/random/BiasedMF-ALS.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-sweep-best/BiasedMF-ALS.json --recommendations=runs/random-sweep-best/BiasedMF-ALS-recs.parquet --predictions=runs/random-sweep-best/BiasedMF-ALS-preds.parquet BiasedMF-ALS
    outs:
      - runs/random-sweep-best/BiasedMF-ALS.json
      - runs/random-sweep-best/BiasedMF-ALS-recs.parquet
      - runs/random-sweep-best/BiasedMF-ALS-preds.parquet
    deps:
      - ../../codex/models/BiasedMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/BiasedMF-ALS.json
  run-random-default-ImplicitMF-ALS:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/ImplicitMF-ALS.json --recommendations=runs/random-default/ImplicitMF-ALS-recs.parquet ImplicitMF-ALS
    outs:
      - runs/random-default/ImplicitMF-ALS.json
      - runs/random-default/ImplicitMF-ALS-recs.parquet
    deps:
      - ../../codex/models/ImplicitMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-ImplicitMF-ALS:
    cmd: >-
      python ../../action.py generate --param-file=sweeps/random/ImplicitMF-ALS.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-sweep-best/ImplicitMF-ALS.json --recommendations=runs/random-sweep-best/ImplicitMF-ALS-recs.parquet ImplicitMF-ALS
    outs:
      - runs/random-sweep-best/ImplicitMF-ALS.json
      - runs/random-sweep-best/ImplicitMF-ALS-recs.parquet
    deps:
      - ../../codex/models/ImplicitMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/ImplicitMF-ALS.json
  run-random-default-IKNN-Explicit:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/IKNN-Explicit.json --recommendations=runs/random-default/IKNN-Explicit-recs.parquet --predictions=runs/random-default/IKNN-Explicit-preds.parquet IKNN-Explicit
    outs:
      - runs/random-default/IKNN-Explicit.json
      - runs/random-default/IKNN-Explicit-recs.parquet
      - runs/random-default/IKNN-Explicit-preds.parquet
    deps:
      - ../../codex/models/IKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN-Explicit:
    cmd: >-
      python ../../action.py generate --param-file=sweeps/random/IKNN-Explicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-sweep-best/IKNN-Explicit.json --recommendations=runs/random-sweep-best/IKNN-Explicit-recs.parquet --predictions=runs/random-sweep-best/IKNN-Explicit-preds.parquet IKNN-Explicit
    outs:
      - runs/random-sweep-best/IKNN-Explicit.json
      - runs/random-sweep-best/IKNN-Explicit-recs.parquet
      - runs/random-sweep-best/IKNN-Explicit-preds.parquet
    deps:
      - ../../codex/models/IKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Explicit.json
  run-random-default-IKNN-Implicit:
    cmd: >-
      python ../../action.py generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-default/IKNN-Implicit.json --recommendations=runs/random-default/IKNN-Implicit-recs.parquet IKNN-Implicit
    outs:
      - runs/random-default/IKNN-Implicit.json
      - runs/random-default/IKNN-Implicit-recs.parquet
    deps:
      - ../../codex/models/IKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN-Implicit:
    cmd: >-
      python ../../action.py generate --param-file=sweeps/random/IKNN-Implicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb --stats=runs/random-sweep-best/IKNN-Implicit.json --recommendations=runs/random-sweep-best/IKNN-Implicit-recs.parquet IKNN-Implicit
    outs:
      - runs/random-sweep-best/IKNN-Implicit.json
      - runs/random-sweep-best/IKNN-Implicit-recs.parquet
    deps:
      - ../../codex/models/IKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Implicit.json
