stages:
  import-ml-32m:
    cmd: python ../import-ml.py ml-32m.zip
    deps:
      - ../import-ml.py
      - ../ml-stats.sql
      - ml-32m.zip
    outs:
      - ratings.duckdb
  sweep-random-Bias:
    cmd: >-
      python ../../scripts/sweep.py -p 1 Bias splits/random.duckdb ratings.duckdb sweeps/random/Bias.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/Bias.py
    outs:
      - sweeps/random/Bias.duckdb
  export-random-Bias:
    cmd: python ../../scripts/sweep.py --export sweeps/random/Bias.duckdb
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/Bias.duckdb
    outs:
      - sweeps/random/Bias.csv
      - sweeps/random/Bias.json
  sweep-random-BiasedMF-ALS:
    cmd: >-
      python ../../scripts/sweep.py -p 1 BiasedMF-ALS splits/random.duckdb ratings.duckdb sweeps/random/BiasedMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/BiasedMF_ALS.py
    outs:
      - sweeps/random/BiasedMF-ALS.duckdb
  export-random-BiasedMF-ALS:
    cmd: python ../../scripts/sweep.py --export sweeps/random/BiasedMF-ALS.duckdb
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/BiasedMF-ALS.duckdb
    outs:
      - sweeps/random/BiasedMF-ALS.csv
      - sweeps/random/BiasedMF-ALS.json
  sweep-random-ImplicitMF-ALS:
    cmd: >-
      python ../../scripts/sweep.py -p 1 ImplicitMF-ALS splits/random.duckdb ratings.duckdb sweeps/random/ImplicitMF-ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/ImplicitMF_ALS.py
    outs:
      - sweeps/random/ImplicitMF-ALS.duckdb
  export-random-ImplicitMF-ALS:
    cmd: python ../../scripts/sweep.py --export sweeps/random/ImplicitMF-ALS.duckdb
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/ImplicitMF-ALS.duckdb
    outs:
      - sweeps/random/ImplicitMF-ALS.csv
      - sweeps/random/ImplicitMF-ALS.json
  sweep-random-IKNN-Explicit:
    cmd: >-
      python ../../scripts/sweep.py -p 1 IKNN-Explicit splits/random.duckdb ratings.duckdb sweeps/random/IKNN-Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Explicit.py
    outs:
      - sweeps/random/IKNN-Explicit.duckdb
  export-random-IKNN-Explicit:
    cmd: python ../../scripts/sweep.py --export sweeps/random/IKNN-Explicit.duckdb
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/IKNN-Explicit.duckdb
    outs:
      - sweeps/random/IKNN-Explicit.csv
      - sweeps/random/IKNN-Explicit.json
  sweep-random-IKNN-Implicit:
    cmd: >-
      python ../../scripts/sweep.py -p 1 IKNN-Implicit splits/random.duckdb ratings.duckdb sweeps/random/IKNN-Implicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Implicit.py
    outs:
      - sweeps/random/IKNN-Implicit.duckdb
  export-random-IKNN-Implicit:
    cmd: python ../../scripts/sweep.py --export sweeps/random/IKNN-Implicit.duckdb
    deps:
      - ../../scripts/sweep.py
      - sweeps/random/IKNN-Implicit.duckdb
    outs:
      - sweeps/random/IKNN-Implicit.csv
      - sweeps/random/IKNN-Implicit.json
