stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-32m.zip
    deps:
      - ../ml-stats.sql
      - ml-32m.zip
    outs:
      - ratings.duckdb
  sweep-temporal-grid-Bias:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML32M --split=splits/temporal.toml --test-part=valid Bias sweeps/temporal/Bias-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/temporal/Bias-grid
  export-temporal-grid-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/Bias-grid.json sweeps/temporal/Bias-grid RMSE
    deps:
      - sweeps/temporal/Bias-grid
    outs:
      - sweeps/temporal/Bias-grid.json:
          cache: false
  sweep-temporal-random-Bias:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML32M --split=splits/temporal.toml --test-part=valid Bias sweeps/temporal/Bias-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/temporal/Bias-random
  export-temporal-random-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/Bias-random.json sweeps/temporal/Bias-random RMSE
    deps:
      - sweeps/temporal/Bias-random
    outs:
      - sweeps/temporal/Bias-random.json:
          cache: false
  sweep-temporal-grid-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML32M --split=splits/temporal.toml --test-part=valid BiasedMF-ALS sweeps/temporal/BiasedMF-ALS-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/temporal/BiasedMF-ALS-grid
  export-temporal-grid-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/BiasedMF-ALS-grid.json sweeps/temporal/BiasedMF-ALS-grid RMSE
    deps:
      - sweeps/temporal/BiasedMF-ALS-grid
    outs:
      - sweeps/temporal/BiasedMF-ALS-grid.json:
          cache: false
  sweep-temporal-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML32M --split=splits/temporal.toml --test-part=valid BiasedMF-ALS sweeps/temporal/BiasedMF-ALS-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/temporal/BiasedMF-ALS-random
  export-temporal-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/BiasedMF-ALS-random.json sweeps/temporal/BiasedMF-ALS-random RMSE
    deps:
      - sweeps/temporal/BiasedMF-ALS-random
    outs:
      - sweeps/temporal/BiasedMF-ALS-random.json:
          cache: false
  sweep-temporal-grid-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML32M --split=splits/temporal.toml --test-part=valid IKNN-Explicit sweeps/temporal/IKNN-Explicit-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/temporal/IKNN-Explicit-grid
  export-temporal-grid-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Explicit-grid.json sweeps/temporal/IKNN-Explicit-grid RMSE
    deps:
      - sweeps/temporal/IKNN-Explicit-grid
    outs:
      - sweeps/temporal/IKNN-Explicit-grid.json:
          cache: false
  sweep-temporal-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML32M --split=splits/temporal.toml --test-part=valid IKNN-Explicit sweeps/temporal/IKNN-Explicit-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/temporal/IKNN-Explicit-random
  export-temporal-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Explicit-random.json sweeps/temporal/IKNN-Explicit-random RMSE
    deps:
      - sweeps/temporal/IKNN-Explicit-random
    outs:
      - sweeps/temporal/IKNN-Explicit-random.json:
          cache: false
  sweep-temporal-grid-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML32M --split=splits/temporal.toml --test-part=valid IKNN-Implicit sweeps/temporal/IKNN-Implicit-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/temporal/IKNN-Implicit-grid
  export-temporal-grid-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Implicit-grid.json sweeps/temporal/IKNN-Implicit-grid RBP
    deps:
      - sweeps/temporal/IKNN-Implicit-grid
    outs:
      - sweeps/temporal/IKNN-Implicit-grid.json:
          cache: false
  sweep-temporal-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML32M --split=splits/temporal.toml --test-part=valid IKNN-Implicit sweeps/temporal/IKNN-Implicit-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/temporal/IKNN-Implicit-random
  export-temporal-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Implicit-random.json sweeps/temporal/IKNN-Implicit-random RBP
    deps:
      - sweeps/temporal/IKNN-Implicit-random
    outs:
      - sweeps/temporal/IKNN-Implicit-random.json:
          cache: false
  sweep-temporal-grid-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --grid --ds-name=ML32M --split=splits/temporal.toml --test-part=valid ImplicitMF-ALS sweeps/temporal/ImplicitMF-ALS-grid
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/temporal/ImplicitMF-ALS-grid
  export-temporal-grid-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/ImplicitMF-ALS-grid.json sweeps/temporal/ImplicitMF-ALS-grid RBP
    deps:
      - sweeps/temporal/ImplicitMF-ALS-grid
    outs:
      - sweeps/temporal/ImplicitMF-ALS-grid.json:
          cache: false
  sweep-temporal-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --random --ds-name=ML32M --split=splits/temporal.toml --test-part=valid ImplicitMF-ALS sweeps/temporal/ImplicitMF-ALS-random
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/temporal/ImplicitMF-ALS-random
  export-temporal-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/ImplicitMF-ALS-random.json sweeps/temporal/ImplicitMF-ALS-random RBP
    deps:
      - sweeps/temporal/ImplicitMF-ALS-random
    outs:
      - sweeps/temporal/ImplicitMF-ALS-random.json:
          cache: false
  run-temporal-default-Bias:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/Bias Bias
    outs:
      - runs/temporal-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-grid-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/Bias-grid.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-grid-best/Bias Bias
    outs:
      - runs/temporal-grid-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/Bias-grid.json
  run-temporal-random-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/Bias-random.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-random-best/Bias Bias
    outs:
      - runs/temporal-random-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/Bias-random.json
  run-temporal-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-grid-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/BiasedMF-ALS-grid.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-grid-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-grid-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/BiasedMF-ALS-grid.json
  run-temporal-random-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/BiasedMF-ALS-random.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-random-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-random-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/BiasedMF-ALS-random.json
  run-temporal-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-grid-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Explicit-grid.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-grid-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-grid-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Explicit-grid.json
  run-temporal-random-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Explicit-random.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-random-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-random-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Explicit-random.json
  run-temporal-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-grid-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Implicit-grid.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-grid-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-grid-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Implicit-grid.json
  run-temporal-random-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Implicit-random.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-random-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-random-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Implicit-random.json
  run-temporal-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-grid-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/ImplicitMF-ALS-grid.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-grid-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-grid-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/ImplicitMF-ALS-grid.json
  run-temporal-random-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/ImplicitMF-ALS-random.json --test-part=test --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-random-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-random-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/ImplicitMF-ALS-random.json
  run-temporal-default-Popular:
    cmd: >-
      lenskit-codex generate --default --ds-name=ML32M --split=splits/temporal.toml -o runs/temporal-default/Popular Popular
    outs:
      - runs/temporal-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/temporal.toml
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics -S run-summary.csv -U run-user-metrics.parquet -L runs/manifest.csv
    deps:
      - runs/temporal-default/Bias
      - runs/temporal-grid-best/Bias
      - runs/temporal-random-best/Bias
      - runs/temporal-default/BiasedMF-ALS
      - runs/temporal-grid-best/BiasedMF-ALS
      - runs/temporal-random-best/BiasedMF-ALS
      - runs/temporal-default/IKNN-Explicit
      - runs/temporal-grid-best/IKNN-Explicit
      - runs/temporal-random-best/IKNN-Explicit
      - runs/temporal-default/IKNN-Implicit
      - runs/temporal-grid-best/IKNN-Implicit
      - runs/temporal-random-best/IKNN-Implicit
      - runs/temporal-default/ImplicitMF-ALS
      - runs/temporal-grid-best/ImplicitMF-ALS
      - runs/temporal-random-best/ImplicitMF-ALS
      - runs/temporal-default/Popular
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
