[settings.python]
uv_venv_auto = true

[tools]
usage = "latest"
# needed when we are installing git deps
rust = "stable"
cargo-binstall = "latest"
"github:quarto-dev/quarto-cli" = "1.9"
go-jsonnet = "latest"
uv = "latest"
# dev support servers
tombi = "latest"
ruff = "latest"
ty = "latest"
dprint = "latest"
"pipx:tclint" = "latest"
hk = "latest"
fd = "latest"
"cargo:guartcl" = "latest"

[tools."pipx:dvc"]
version = "3"
extras = "s3,webdav"

[env]
JIMLIB = "{{config_root}}/src/tcl/pipeline:{{config_root}}/src/tcl/lib"
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"
