[settings.python]
uv_venv_auto = true

[tools]
dprint = "latest"
go-jsonnet = "latest"
usage = "latest"
ruff = "latest"
uv = "latest"
"github:quarto-dev/quarto-cli" = "1.9"

[env]
TCLLIBPATH = "{{config_root}}/src/tcl"
