[settings.python]
uv_venv_auto = true

[tools]
usage = "latest"
"github:quarto-dev/quarto-cli" = "1.9"
go-jsonnet = "latest"
uv = "latest"
# dev support servers
dprint = "latest"
tombi = "latest"
"pipx:tclint" = "latest"
hk = "latest"

[env]
TCLLIBPATH = "{{config_root}}/src/tcl"
JIMLIB = "{{config_root}}/src/tcl/pipeline:{{config_root}}/src/tcl/lib"
