source = "../ML100K"

[[replacements]]
match = "ML100K"
replace = "ML25M"

[documents.description]
[documents.bias]
[documents.als-implicitmf]
[documents.als-biasedmf]
[documents.iknn-explicit]
[documents.iknn-implicit]
