source = "../ML100K"

[[replacements]]
match = "ML100K"
replace = "ML25M"

[[replacements]]
match = "random"
replace = "temporal"

[documents.description]
# [documents.summary]
[documents.bias]
[documents.als-implicitmf]
[documents.als-biasedmf]
[documents.iknn-explicit]
[documents.iknn-implicit]
