stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/temporal-default/bias
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-25m.zip dataset
    deps:
      - ml-25m.zip
    outs:
      - dataset
  run-temporal-default-bias:
    cmd: lenskit codex generate --default --ds-name=../.. --split=splits/temporal.toml
      -o runs/temporal-default/bias bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal-default/bias
  stats:
    cmd: lenskit codex sql -D ds_name=ML25M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
