stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-25m.zip
    deps:
      - ../ml-stats.sql
      - ml-25m.zip
    outs:
      - ratings.duckdb
  sweep-temporal-Bias:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML25M --split=splits/temporal.toml --test-part=valid Bias sweeps/temporal/Bias
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/temporal/Bias
  export-temporal-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/Bias.json sweeps/temporal/Bias RMSE
    deps:
      - sweeps/temporal/Bias
    outs:
      - sweeps/temporal/Bias.json:
          cache: false
  sweep-temporal-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML25M --split=splits/temporal.toml --test-part=valid BiasedMF-ALS sweeps/temporal/BiasedMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/temporal/BiasedMF-ALS
  export-temporal-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/BiasedMF-ALS.json sweeps/temporal/BiasedMF-ALS RMSE
    deps:
      - sweeps/temporal/BiasedMF-ALS
    outs:
      - sweeps/temporal/BiasedMF-ALS.json:
          cache: false
  sweep-temporal-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML25M --split=splits/temporal.toml --test-part=valid IKNN-Explicit sweeps/temporal/IKNN-Explicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/temporal/IKNN-Explicit
  export-temporal-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Explicit.json sweeps/temporal/IKNN-Explicit RMSE
    deps:
      - sweeps/temporal/IKNN-Explicit
    outs:
      - sweeps/temporal/IKNN-Explicit.json:
          cache: false
  sweep-temporal-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML25M --split=splits/temporal.toml --test-part=valid IKNN-Implicit sweeps/temporal/IKNN-Implicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/temporal/IKNN-Implicit
  export-temporal-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Implicit.json sweeps/temporal/IKNN-Implicit RBP
    deps:
      - sweeps/temporal/IKNN-Implicit
    outs:
      - sweeps/temporal/IKNN-Implicit.json:
          cache: false
  sweep-temporal-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML25M --split=splits/temporal.toml --test-part=valid ImplicitMF-ALS sweeps/temporal/ImplicitMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/temporal/ImplicitMF-ALS
  export-temporal-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/ImplicitMF-ALS.json sweeps/temporal/ImplicitMF-ALS RBP
    deps:
      - sweeps/temporal/ImplicitMF-ALS
    outs:
      - sweeps/temporal/ImplicitMF-ALS.json:
          cache: false
  run-temporal-default-Bias:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/Bias Bias
    outs:
      - runs/temporal-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/Bias.json --split=splits/temporal.toml --test-part=test -o runs/temporal-sweep-best/Bias Bias
    outs:
      - runs/temporal-sweep-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/Bias.json
  run-temporal-default-Popular:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/Popular Popular
    outs:
      - runs/temporal-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/BiasedMF-ALS.json --split=splits/temporal.toml --test-part=test -o runs/temporal-sweep-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-sweep-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/BiasedMF-ALS.json
  run-temporal-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Explicit.json --split=splits/temporal.toml --test-part=test -o runs/temporal-sweep-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-sweep-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Explicit.json
  run-temporal-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Implicit.json --split=splits/temporal.toml --test-part=test -o runs/temporal-sweep-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-sweep-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Implicit.json
  run-temporal-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml -o runs/temporal-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/ImplicitMF-ALS.json --split=splits/temporal.toml --test-part=test -o runs/temporal-sweep-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-sweep-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/ImplicitMF-ALS.json
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics run-metrics.duckdb --view-script=../ml-run-metrics.sql runs
    deps: []
    outs:
      - run-metrics.duckdb
