stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/temporal/bias-default
      - runs/temporal/popular-default
      - runs/temporal/bias-random-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-25m.zip dataset
    deps:
      - ml-25m.zip
    outs:
      - dataset
  run-temporal-default-bias:
    cmd: lenskit codex generate --default --ds-name=../.. --split=splits/temporal.toml
      -o runs/temporal/bias-default bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/bias-default
  run-temporal-default-popular:
    cmd: lenskit codex generate --default --ds-name=../.. --split=splits/temporal.toml
      -o runs/temporal/popular-default popular
    deps:
      - ../../src/codex/models/popular.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/popular-default
  run-temporal-random-best-bias:
    cmd: lenskit codex generate --param-file sweeps/temporal/bias-random.json --ds-name=../..
      --split=splits/temporal.toml -o runs/temporal/bias-random-best bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/bias-random.json
    outs:
      - runs/temporal/bias-random-best
  stats:
    cmd: lenskit codex sql -D ds_name=ML25M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
