stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-10m.zip
    deps:
      - ../ml-stats.sql
      - ml-10m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: lenskit-codex split random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  sweep-random-Bias:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 Bias sweeps/random/Bias
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/random/Bias
  export-random-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/Bias.json sweeps/random/Bias RMSE
    deps:
      - sweeps/random/Bias
    outs:
      - sweeps/random/Bias.json:
          cache: false
  sweep-random-HPF:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 HPF sweeps/random/HPF
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/HPF.toml
    outs:
      - sweeps/random/HPF
  export-random-HPF:
    cmd: lenskit-codex sweep export -o sweeps/random/HPF.json sweeps/random/HPF RBP
    deps:
      - sweeps/random/HPF
    outs:
      - sweeps/random/HPF.json:
          cache: false
  sweep-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 BiasedMF-ALS sweeps/random/BiasedMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/random/BiasedMF-ALS
  export-random-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/BiasedMF-ALS.json sweeps/random/BiasedMF-ALS RMSE
    deps:
      - sweeps/random/BiasedMF-ALS
    outs:
      - sweeps/random/BiasedMF-ALS.json:
          cache: false
  sweep-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 IKNN-Explicit sweeps/random/IKNN-Explicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/random/IKNN-Explicit
  export-random-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Explicit.json sweeps/random/IKNN-Explicit RMSE
    deps:
      - sweeps/random/IKNN-Explicit
    outs:
      - sweeps/random/IKNN-Explicit.json:
          cache: false
  sweep-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 IKNN-Implicit sweeps/random/IKNN-Implicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/random/IKNN-Implicit
  export-random-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/IKNN-Implicit.json sweeps/random/IKNN-Implicit RBP
    deps:
      - sweeps/random/IKNN-Implicit
    outs:
      - sweeps/random/IKNN-Implicit.json:
          cache: false
  sweep-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/random.toml --test-part=0 ImplicitMF-ALS sweeps/random/ImplicitMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/random/ImplicitMF-ALS
  export-random-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/random/ImplicitMF-ALS.json sweeps/random/ImplicitMF-ALS RBP
    deps:
      - sweeps/random/ImplicitMF-ALS
    outs:
      - sweeps/random/ImplicitMF-ALS.json:
          cache: false
  sweep-temporal-Bias:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid Bias sweeps/temporal/Bias
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/Bias.toml
    outs:
      - sweeps/temporal/Bias
  export-temporal-Bias:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/Bias.json sweeps/temporal/Bias RMSE
    deps:
      - sweeps/temporal/Bias
    outs:
      - sweeps/temporal/Bias.json:
          cache: false
  sweep-temporal-HPF:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid HPF sweeps/temporal/HPF
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/HPF.toml
    outs:
      - sweeps/temporal/HPF
  export-temporal-HPF:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/HPF.json sweeps/temporal/HPF RBP
    deps:
      - sweeps/temporal/HPF
    outs:
      - sweeps/temporal/HPF.json:
          cache: false
  sweep-temporal-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid BiasedMF-ALS sweeps/temporal/BiasedMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/BiasedMF-ALS.toml
    outs:
      - sweeps/temporal/BiasedMF-ALS
  export-temporal-BiasedMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/BiasedMF-ALS.json sweeps/temporal/BiasedMF-ALS RMSE
    deps:
      - sweeps/temporal/BiasedMF-ALS
    outs:
      - sweeps/temporal/BiasedMF-ALS.json:
          cache: false
  sweep-temporal-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid IKNN-Explicit sweeps/temporal/IKNN-Explicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Explicit.toml
    outs:
      - sweeps/temporal/IKNN-Explicit
  export-temporal-IKNN-Explicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Explicit.json sweeps/temporal/IKNN-Explicit RMSE
    deps:
      - sweeps/temporal/IKNN-Explicit
    outs:
      - sweeps/temporal/IKNN-Explicit.json:
          cache: false
  sweep-temporal-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid IKNN-Implicit sweeps/temporal/IKNN-Implicit
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/IKNN-Implicit.toml
    outs:
      - sweeps/temporal/IKNN-Implicit
  export-temporal-IKNN-Implicit:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/IKNN-Implicit.json sweeps/temporal/IKNN-Implicit RBP
    deps:
      - sweeps/temporal/IKNN-Implicit
    outs:
      - sweeps/temporal/IKNN-Implicit.json:
          cache: false
  sweep-temporal-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep run --ds-name=ML10M --split=splits/temporal.toml --test-part=valid ImplicitMF-ALS sweeps/temporal/ImplicitMF-ALS
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/temporal.toml
      - ratings.duckdb
      - ../../models/ImplicitMF-ALS.toml
    outs:
      - sweeps/temporal/ImplicitMF-ALS
  export-temporal-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex sweep export -o sweeps/temporal/ImplicitMF-ALS.json sweeps/temporal/ImplicitMF-ALS RBP
    deps:
      - sweeps/temporal/ImplicitMF-ALS
    outs:
      - sweeps/temporal/ImplicitMF-ALS.json:
          cache: false
  run-random-default-Bias:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/Bias Bias
    outs:
      - runs/random-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Bias.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/Bias Bias
    outs:
      - runs/random-sweep-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias.json
  run-random-default-HPF:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/HPF HPF
    outs:
      - runs/random-default/HPF
    deps:
      - ../../models/HPF.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-HPF:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/HPF.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/HPF HPF
    outs:
      - runs/random-sweep-best/HPF
    deps:
      - ../../models/HPF.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/HPF.json
  run-random-default-Popular:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/Popular Popular
    outs:
      - runs/random-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/random-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/BiasedMF-ALS.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/random-sweep-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/BiasedMF-ALS.json
  run-random-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Explicit.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/random-sweep-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Explicit.json
  run-random-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN-Implicit.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/random-sweep-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN-Implicit.json
  run-random-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/random.toml --test-part=-0 -o runs/random-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/random-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/ImplicitMF-ALS.json --split=splits/random.toml --test-part=-0 -o runs/random-sweep-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/random-sweep-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/ImplicitMF-ALS.json
  run-temporal-valid-default-Bias:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/Bias Bias
    outs:
      - runs/temporal-valid-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-Bias:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/Bias Bias
    outs:
      - runs/temporal-default/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/Bias.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/Bias Bias
    outs:
      - runs/temporal-sweep-best/Bias
    deps:
      - ../../models/Bias.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/Bias.json
  run-temporal-valid-default-HPF:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/HPF HPF
    outs:
      - runs/temporal-valid-default/HPF
    deps:
      - ../../models/HPF.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-HPF:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/HPF HPF
    outs:
      - runs/temporal-default/HPF
    deps:
      - ../../models/HPF.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-HPF:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/HPF.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/HPF HPF
    outs:
      - runs/temporal-sweep-best/HPF
    deps:
      - ../../models/HPF.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/HPF.json
  run-temporal-valid-default-Popular:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/Popular Popular
    outs:
      - runs/temporal-valid-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-Popular:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/Popular Popular
    outs:
      - runs/temporal-default/Popular
    deps:
      - ../../models/Popular.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-valid-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-valid-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-default/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-BiasedMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/BiasedMF-ALS.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/BiasedMF-ALS BiasedMF-ALS
    outs:
      - runs/temporal-sweep-best/BiasedMF-ALS
    deps:
      - ../../models/BiasedMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/BiasedMF-ALS.json
  run-temporal-valid-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-valid-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-default/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-IKNN-Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Explicit.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/IKNN-Explicit IKNN-Explicit
    outs:
      - runs/temporal-sweep-best/IKNN-Explicit
    deps:
      - ../../models/IKNN-Explicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Explicit.json
  run-temporal-valid-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-valid-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-default/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-IKNN-Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/IKNN-Implicit.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/IKNN-Implicit IKNN-Implicit
    outs:
      - runs/temporal-sweep-best/IKNN-Implicit
    deps:
      - ../../models/IKNN-Implicit.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/IKNN-Implicit.json
  run-temporal-valid-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=valid -o runs/temporal-valid-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-valid-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-default-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --default --split=splits/temporal.toml --test-part=test -o runs/temporal-default/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-default/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
  run-temporal-sweep-best-ImplicitMF-ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/temporal/ImplicitMF-ALS.json --split=splits/temporal.toml --test-part=-0 -o runs/temporal-sweep-best/ImplicitMF-ALS ImplicitMF-ALS
    outs:
      - runs/temporal-sweep-best/ImplicitMF-ALS
    deps:
      - ../../models/ImplicitMF-ALS.toml
      - ratings.duckdb
      - splits/temporal.toml
      - sweeps/temporal/ImplicitMF-ALS.json
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics run-metrics.duckdb --view-script=../ml-run-metrics.sql runs
    deps: []
    outs:
      - run-metrics.duckdb
