stages:
  import-ml-10m:
    cmd: python ../import-ml.py ml-10m.zip
    deps:
      - ../import-ml.py
      - ../ml-stats.sql
      - ml-10m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: python ../../../scripts/split.py random.toml
    wdir: splits
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
