stages:
  import:
    cmd: lenskit-codex movielens import --stat-sql=../ml-stats.sql ml-10m.zip
    deps:
      - ../ml-stats.sql
      - ml-10m.zip
    outs:
      - ratings.duckdb
  split-random:
    cmd: lenskit-codex split random.toml
    wdir: splits
    params:
      - ../../../config.toml:
          - random.seed
    deps:
      - random.toml
      - ../ratings.duckdb
    outs:
      - random.duckdb
  sweep-random-BiasedMF_ALS:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb BiasedMF_ALS sweeps/random/BiasedMF_ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/BiasedMF_ALS.py
    outs:
      - sweeps/random/BiasedMF_ALS.duckdb
  export-random-BiasedMF_ALS:
    cmd: lenskit-codex sweep export sweeps/random/BiasedMF_ALS.duckdb rmse
    deps:
      - sweeps/random/BiasedMF_ALS.duckdb
    outs:
      - sweeps/random/BiasedMF_ALS.csv
      - sweeps/random/BiasedMF_ALS.json:
          cache: false
  sweep-random-Bias:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb Bias sweeps/random/Bias.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/Bias.py
    outs:
      - sweeps/random/Bias.duckdb
  export-random-Bias:
    cmd: lenskit-codex sweep export sweeps/random/Bias.duckdb rmse
    deps:
      - sweeps/random/Bias.duckdb
    outs:
      - sweeps/random/Bias.csv
      - sweeps/random/Bias.json:
          cache: false
  sweep-random-HPF:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb HPF sweeps/random/HPF.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/HPF.py
    outs:
      - sweeps/random/HPF.duckdb
  export-random-HPF:
    cmd: lenskit-codex sweep export sweeps/random/HPF.duckdb ndcg
    deps:
      - sweeps/random/HPF.duckdb
    outs:
      - sweeps/random/HPF.csv
      - sweeps/random/HPF.json:
          cache: false
  sweep-random-IKNN_Explicit:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb IKNN_Explicit sweeps/random/IKNN_Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Explicit.py
    outs:
      - sweeps/random/IKNN_Explicit.duckdb
  export-random-IKNN_Explicit:
    cmd: lenskit-codex sweep export sweeps/random/IKNN_Explicit.duckdb rmse
    deps:
      - sweeps/random/IKNN_Explicit.duckdb
    outs:
      - sweeps/random/IKNN_Explicit.csv
      - sweeps/random/IKNN_Explicit.json:
          cache: false
  sweep-random-IKNN_Implicit:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb IKNN_Implicit sweeps/random/IKNN_Implicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/IKNN_Implicit.py
    outs:
      - sweeps/random/IKNN_Implicit.duckdb
  export-random-IKNN_Implicit:
    cmd: lenskit-codex sweep export sweeps/random/IKNN_Implicit.duckdb ndcg
    deps:
      - sweeps/random/IKNN_Implicit.duckdb
    outs:
      - sweeps/random/IKNN_Implicit.csv
      - sweeps/random/IKNN_Implicit.json:
          cache: false
  sweep-random-Implicit_BPR:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb Implicit_BPR sweeps/random/Implicit_BPR.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/Implicit_BPR.py
    outs:
      - sweeps/random/Implicit_BPR.duckdb
  export-random-Implicit_BPR:
    cmd: lenskit-codex sweep export sweeps/random/Implicit_BPR.duckdb ndcg
    deps:
      - sweeps/random/Implicit_BPR.duckdb
    outs:
      - sweeps/random/Implicit_BPR.csv
      - sweeps/random/Implicit_BPR.json:
          cache: false
  sweep-random-ImplicitMF_ALS:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb ImplicitMF_ALS sweeps/random/ImplicitMF_ALS.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/ImplicitMF_ALS.py
    outs:
      - sweeps/random/ImplicitMF_ALS.duckdb
  export-random-ImplicitMF_ALS:
    cmd: lenskit-codex sweep export sweeps/random/ImplicitMF_ALS.duckdb ndcg
    deps:
      - sweeps/random/ImplicitMF_ALS.duckdb
    outs:
      - sweeps/random/ImplicitMF_ALS.csv
      - sweeps/random/ImplicitMF_ALS.json:
          cache: false
  sweep-random-UKNN_Explicit:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb UKNN_Explicit sweeps/random/UKNN_Explicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/UKNN_Explicit.py
    outs:
      - sweeps/random/UKNN_Explicit.duckdb
  export-random-UKNN_Explicit:
    cmd: lenskit-codex sweep export sweeps/random/UKNN_Explicit.duckdb rmse
    deps:
      - sweeps/random/UKNN_Explicit.duckdb
    outs:
      - sweeps/random/UKNN_Explicit.csv
      - sweeps/random/UKNN_Explicit.json:
          cache: false
  sweep-random-UKNN_Implicit:
    cmd: >-
      lenskit-codex sweep run -p 0 --ratings=ratings.duckdb --assignments=splits/random.duckdb UKNN_Implicit sweeps/random/UKNN_Implicit.duckdb
    params:
      - ../../config.toml:
          - random.seed
    deps:
      - splits/random.duckdb
      - ratings.duckdb
      - ../../codex/models/UKNN_Implicit.py
    outs:
      - sweeps/random/UKNN_Implicit.duckdb
  export-random-UKNN_Implicit:
    cmd: lenskit-codex sweep export sweeps/random/UKNN_Implicit.duckdb ndcg
    deps:
      - sweeps/random/UKNN_Implicit.duckdb
    outs:
      - sweeps/random/UKNN_Implicit.csv
      - sweeps/random/UKNN_Implicit.json:
          cache: false
  run-random-default-BiasedMF_ALS:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/BiasedMF_ALS BiasedMF_ALS
    outs:
      - runs/random-default/BiasedMF_ALS
    deps:
      - ../../codex/models/BiasedMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-BiasedMF_ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/BiasedMF_ALS.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/BiasedMF_ALS.duckdb BiasedMF_ALS
    outs:
      - runs/random-sweep-best/BiasedMF_ALS.duckdb
    deps:
      - ../../codex/models/BiasedMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/BiasedMF_ALS.json
  run-random-default-Bias:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/Bias Bias
    outs:
      - runs/random-default/Bias
    deps:
      - ../../codex/models/Bias.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-Bias:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Bias.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/Bias.duckdb Bias
    outs:
      - runs/random-sweep-best/Bias.duckdb
    deps:
      - ../../codex/models/Bias.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Bias.json
  run-random-default-HPF:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/HPF HPF
    outs:
      - runs/random-default/HPF
    deps:
      - ../../codex/models/HPF.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-HPF:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/HPF.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/HPF.duckdb HPF
    outs:
      - runs/random-sweep-best/HPF.duckdb
    deps:
      - ../../codex/models/HPF.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/HPF.json
  run-random-default-IKNN_Explicit:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/IKNN_Explicit IKNN_Explicit
    outs:
      - runs/random-default/IKNN_Explicit
    deps:
      - ../../codex/models/IKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN_Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN_Explicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/IKNN_Explicit.duckdb IKNN_Explicit
    outs:
      - runs/random-sweep-best/IKNN_Explicit.duckdb
    deps:
      - ../../codex/models/IKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN_Explicit.json
  run-random-default-IKNN_Implicit:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/IKNN_Implicit IKNN_Implicit
    outs:
      - runs/random-default/IKNN_Implicit
    deps:
      - ../../codex/models/IKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-IKNN_Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/IKNN_Implicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/IKNN_Implicit.duckdb IKNN_Implicit
    outs:
      - runs/random-sweep-best/IKNN_Implicit.duckdb
    deps:
      - ../../codex/models/IKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/IKNN_Implicit.json
  run-random-default-Implicit_BPR:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/Implicit_BPR Implicit_BPR
    outs:
      - runs/random-default/Implicit_BPR
    deps:
      - ../../codex/models/Implicit_BPR.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-Implicit_BPR:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/Implicit_BPR.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/Implicit_BPR.duckdb Implicit_BPR
    outs:
      - runs/random-sweep-best/Implicit_BPR.duckdb
    deps:
      - ../../codex/models/Implicit_BPR.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/Implicit_BPR.json
  run-random-default-ImplicitMF_ALS:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/ImplicitMF_ALS ImplicitMF_ALS
    outs:
      - runs/random-default/ImplicitMF_ALS
    deps:
      - ../../codex/models/ImplicitMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-ImplicitMF_ALS:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/ImplicitMF_ALS.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/ImplicitMF_ALS.duckdb ImplicitMF_ALS
    outs:
      - runs/random-sweep-best/ImplicitMF_ALS.duckdb
    deps:
      - ../../codex/models/ImplicitMF_ALS.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/ImplicitMF_ALS.json
  run-random-default-Popular:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/Popular Popular
    outs:
      - runs/random-default/Popular
    deps:
      - ../../codex/models/Popular.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-default-UKNN_Explicit:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/UKNN_Explicit UKNN_Explicit
    outs:
      - runs/random-default/UKNN_Explicit
    deps:
      - ../../codex/models/UKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-UKNN_Explicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/UKNN_Explicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/UKNN_Explicit.duckdb UKNN_Explicit
    outs:
      - runs/random-sweep-best/UKNN_Explicit.duckdb
    deps:
      - ../../codex/models/UKNN_Explicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/UKNN_Explicit.json
  run-random-default-UKNN_Implicit:
    cmd: >-
      lenskit-codex generate --default --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-default/UKNN_Implicit UKNN_Implicit
    outs:
      - runs/random-default/UKNN_Implicit
    deps:
      - ../../codex/models/UKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
  run-random-sweep-best-UKNN_Implicit:
    cmd: >-
      lenskit-codex generate --param-file=sweeps/random/UKNN_Implicit.json --test-part=-0 --assignments=splits/random.duckdb --ratings=ratings.duckdb -o runs/random-sweep-best/UKNN_Implicit.duckdb UKNN_Implicit
    outs:
      - runs/random-sweep-best/UKNN_Implicit.duckdb
    deps:
      - ../../codex/models/UKNN_Implicit.py
      - ratings.duckdb
      - splits/random.duckdb
      - sweeps/random/UKNN_Implicit.json
  collect-metrics:
    cmd: >-
      lenskit-codex collect metrics run-metrics.duckdb --view-script=../ml-run-metrics.sql runs
    deps:
      - runs/random-sweep-best/BiasedMF_ALS.duckdb
      - runs/random-sweep-best/Bias.duckdb
      - runs/random-sweep-best/HPF.duckdb
      - runs/random-sweep-best/IKNN_Explicit.duckdb
      - runs/random-sweep-best/IKNN_Implicit.duckdb
      - runs/random-sweep-best/Implicit_BPR.duckdb
      - runs/random-sweep-best/ImplicitMF_ALS.duckdb
      - runs/random-sweep-best/UKNN_Explicit.duckdb
      - runs/random-sweep-best/UKNN_Implicit.duckdb
    outs:
      - run-metrics.duckdb
