stages:
  import-ml-10m:
    cmd: python ../import-ml.py ml-10m.zip
    deps:
    - ../import-ml.py
    - ml-10m.zip
    outs:
    - ratings.parquet
  ml-10m-stats:
    cmd: python ../../scripts/duckdb-sql.py -d stats.duckdb ../ml-stats.sql
    deps:
    - ../ml-stats.sql
    - ratings.parquet
    outs:
    - stats.duckdb
