[search]
metric = "RBP"
max_points = 30

[space.scorer]
l1_reg = { type = "float", min = 0.01, max = 1000, scale = "log" }
l2_reg = { type = "float", min = 0.01, max = 1000, scale = "log" }

[pipeline]
file = "pipeline.toml"
