[search]
metric = "RMSE"
max_epochs = 50
num_gpus = 0.2

[space.scorer]
embedding_size_exp = { type = "int", min = 3, max = 10, scale = "log" }
regularization = { type = "float", min = 1e-4, max = 10, scale = "log" }
learning_rate = { type = "float", min = 1e-3, max = 0.1, scale = "log" }

[pipeline]
file = "pipeline.toml"
