[meta]
name = "lightgcn-logistic"

[options]
base = "std:topn"

[components.scorer]
class = "lenskit.flexmf.FlexMFImplicitScorer"

[components.scorer.config]
loss = "logistic"
reg_method = "AdamW"
user_bias = true
convolution_layers = 2
