stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/temporal/bias-default
      - runs/temporal/iknn-explicit-default
      - runs/temporal/iknn-implicit-default
      - runs/temporal/implicit-bpr-default
      - runs/temporal/popular-default
      - runs/temporal/bias-random-best
      - runs/temporal/iknn-explicit-random-best
      - runs/temporal/iknn-implicit-random-best
      - runs/temporal/implicit-bpr-random-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-20m.zip dataset
    deps:
      - ml-20m.zip
    outs:
      - dataset
  run-temporal-default-bias:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/bias-default bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/bias-default
  run-temporal-default-iknn-explicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/iknn-explicit-default iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/iknn-explicit-default
  run-temporal-default-iknn-implicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/iknn-implicit-default iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/iknn-implicit-default
  run-temporal-default-implicit-bpr:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/implicit-bpr-default implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/implicit-bpr-default
  run-temporal-default-popular:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/popular-default popular
    deps:
      - ../../src/codex/models/popular.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/popular-default
  run-temporal-random-best-bias:
    cmd: lenskit codex generate --param-file sweeps/temporal/bias-random.json --ds-name=ML20M
      --split=splits/temporal.toml -o runs/temporal/bias-random-best bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/bias-random.json
    outs:
      - runs/temporal/bias-random-best
  run-temporal-random-best-iknn-explicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/iknn-explicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/iknn-explicit-random-best
      iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/iknn-explicit-random.json
    outs:
      - runs/temporal/iknn-explicit-random-best
  run-temporal-random-best-iknn-implicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/iknn-implicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/iknn-implicit-random-best
      iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/iknn-implicit-random.json
    outs:
      - runs/temporal/iknn-implicit-random-best
  run-temporal-random-best-implicit-bpr:
    cmd: lenskit codex generate --param-file sweeps/temporal/implicit-bpr-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/implicit-bpr-random-best
      implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/implicit-bpr-random.json
    outs:
      - runs/temporal/implicit-bpr-random-best
  stats:
    cmd: lenskit codex sql -D ds_name=ML20M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
