stages:
  collect-metrics:
    cmd: lenskit codex collect metrics -S run-summary.csv -U run-user-metrics.parquet
      -L runs/manifest.csv
    deps:
      - runs/temporal/als-biased-default
      - runs/temporal/als-implicit-default
      - runs/temporal/bias-default
      - runs/temporal/flexmf-explicit-default
      - runs/temporal/iknn-explicit-default
      - runs/temporal/iknn-implicit-default
      - runs/temporal/implicit-bpr-default
      - runs/temporal/popular-default
      - runs/temporal/als-biased-random-best
      - runs/temporal/als-implicit-random-best
      - runs/temporal/bias-random-best
      - runs/temporal/flexmf-explicit-random-best
      - runs/temporal/iknn-explicit-random-best
      - runs/temporal/iknn-implicit-random-best
      - runs/temporal/implicit-bpr-random-best
    outs:
      - run-summary.csv
      - run-user-metrics.parquet
  import:
    cmd: lenskit data convert --movielens ml-20m.zip dataset
    deps:
      - ml-20m.zip
    outs:
      - dataset
  run-temporal-default-als-biased:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/als-biased-default als-biased
    deps:
      - ../../src/codex/models/als_biased.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/als-biased-default
  run-temporal-default-als-implicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/als-implicit-default als-implicit
    deps:
      - ../../src/codex/models/als_implicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/als-implicit-default
  run-temporal-default-bias:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/bias-default bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/bias-default
  run-temporal-default-flexmf-explicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/flexmf-explicit-default flexmf-explicit
    deps:
      - ../../src/codex/models/flexmf_explicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/flexmf-explicit-default
  run-temporal-default-iknn-explicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/iknn-explicit-default iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/iknn-explicit-default
  run-temporal-default-iknn-implicit:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/iknn-implicit-default iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/iknn-implicit-default
  run-temporal-default-implicit-bpr:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/implicit-bpr-default implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/implicit-bpr-default
  run-temporal-default-popular:
    cmd: lenskit codex generate --default --ds-name=ML20M --split=splits/temporal.toml
      -o runs/temporal/popular-default popular
    deps:
      - ../../src/codex/models/popular.py
      - dataset
      - splits/temporal.toml
    outs:
      - runs/temporal/popular-default
  run-temporal-random-best-als-biased:
    cmd: lenskit codex generate --param-file sweeps/temporal/als-biased-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/als-biased-random-best
      als-biased
    deps:
      - ../../src/codex/models/als_biased.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/als-biased-random.json
    outs:
      - runs/temporal/als-biased-random-best
  run-temporal-random-best-als-implicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/als-implicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/als-implicit-random-best
      als-implicit
    deps:
      - ../../src/codex/models/als_implicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/als-implicit-random.json
    outs:
      - runs/temporal/als-implicit-random-best
  run-temporal-random-best-bias:
    cmd: lenskit codex generate --param-file sweeps/temporal/bias-random.json --ds-name=ML20M
      --split=splits/temporal.toml -o runs/temporal/bias-random-best bias
    deps:
      - ../../src/codex/models/bias.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/bias-random.json
    outs:
      - runs/temporal/bias-random-best
  run-temporal-random-best-flexmf-explicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/flexmf-explicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/flexmf-explicit-random-best
      flexmf-explicit
    deps:
      - ../../src/codex/models/flexmf_explicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/flexmf-explicit-random.json
    outs:
      - runs/temporal/flexmf-explicit-random-best
  run-temporal-random-best-iknn-explicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/iknn-explicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/iknn-explicit-random-best
      iknn-explicit
    deps:
      - ../../src/codex/models/iknn_explicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/iknn-explicit-random.json
    outs:
      - runs/temporal/iknn-explicit-random-best
  run-temporal-random-best-iknn-implicit:
    cmd: lenskit codex generate --param-file sweeps/temporal/iknn-implicit-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/iknn-implicit-random-best
      iknn-implicit
    deps:
      - ../../src/codex/models/iknn_implicit.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/iknn-implicit-random.json
    outs:
      - runs/temporal/iknn-implicit-random-best
  run-temporal-random-best-implicit-bpr:
    cmd: lenskit codex generate --param-file sweeps/temporal/implicit-bpr-random.json
      --ds-name=ML20M --split=splits/temporal.toml -o runs/temporal/implicit-bpr-random-best
      implicit-bpr
    deps:
      - ../../src/codex/models/implicit_bpr.py
      - dataset
      - splits/temporal.toml
      - sweeps/temporal/implicit-bpr-random.json
    outs:
      - runs/temporal/implicit-bpr-random-best
  stats:
    cmd: lenskit codex sql -D ds_name=ML20M -f ../ml-stats.sql stats.duckdb
    deps:
      - ../ml-stats.sql
      - dataset
    outs:
      - stats.duckdb
  sweep-als-biased-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RMSE als-biased sweeps/temporal/als-biased-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/als_biased.py
    outs:
      - sweeps/temporal/als-biased-random
      - sweeps/temporal/als-biased-random.json:
          cache: false
  sweep-als-implicit-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RBP als-implicit sweeps/temporal/als-implicit-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/als_implicit.py
    outs:
      - sweeps/temporal/als-implicit-random
      - sweeps/temporal/als-implicit-random.json:
          cache: false
  sweep-bias-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RMSE bias sweeps/temporal/bias-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/bias.py
    outs:
      - sweeps/temporal/bias-random
      - sweeps/temporal/bias-random.json:
          cache: false
  sweep-flexmf-explicit-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RMSE flexmf-explicit sweeps/temporal/flexmf-explicit-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/flexmf_explicit.py
    outs:
      - sweeps/temporal/flexmf-explicit-random
      - sweeps/temporal/flexmf-explicit-random.json:
          cache: false
  sweep-iknn-explicit-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RMSE iknn-explicit sweeps/temporal/iknn-explicit-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/iknn_explicit.py
    outs:
      - sweeps/temporal/iknn-explicit-random
      - sweeps/temporal/iknn-explicit-random.json:
          cache: false
  sweep-iknn-implicit-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RBP iknn-implicit sweeps/temporal/iknn-implicit-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/iknn_implicit.py
    outs:
      - sweeps/temporal/iknn-implicit-random
      - sweeps/temporal/iknn-implicit-random.json:
          cache: false
  sweep-implicit-bpr-temporal-random:
    cmd: lenskit codex search --split=splits/temporal.toml --test-part=valid --random
      --metric=RBP implicit-bpr sweeps/temporal/implicit-bpr-random
    deps:
      - splits/temporal.toml
      - ../../src/codex/models/implicit_bpr.py
    outs:
      - sweeps/temporal/implicit-bpr-random
      - sweeps/temporal/implicit-bpr-random.json:
          cache: false
