[search]
metric = "RMSE"

[space.scorer]
max_nbrs = { type = "int", min = 2, max = 50 }
min_nbrs = { type = "int", min = 1, max = 5 }
min_sim = { type = "float", min = 1.0e-6, max = 0.1, scale = "log" }

[pipeline]
file = "pipeline.toml"
