stages:
  scan-bench-users:
    cmd: python ../../action.py amazon collect-ids --user -D user-ids.duckdb data
    deps:
      - data/Arts_Crafts_and_Sewing.test.csv.gz
      - data/Arts_Crafts_and_Sewing.train.csv.gz
      - data/Arts_Crafts_and_Sewing.valid.csv.gz
      - data/Automotive.test.csv.gz
      - data/Automotive.train.csv.gz
      - data/Automotive.valid.csv.gz
      - data/Baby_Products.test.csv.gz
      - data/Baby_Products.train.csv.gz
      - data/Baby_Products.valid.csv.gz
      - data/Beauty_and_Personal_Care.test.csv.gz
      - data/Beauty_and_Personal_Care.train.csv.gz
      - data/Beauty_and_Personal_Care.valid.csv.gz
      - data/Books.test.csv.gz
      - data/Books.train.csv.gz
      - data/Books.valid.csv.gz
      - data/CDs_and_Vinyl.test.csv.gz
      - data/CDs_and_Vinyl.train.csv.gz
      - data/CDs_and_Vinyl.valid.csv.gz
      - data/Cell_Phones_and_Accessories.test.csv.gz
      - data/Cell_Phones_and_Accessories.train.csv.gz
      - data/Cell_Phones_and_Accessories.valid.csv.gz
      - data/Clothing_Shoes_and_Jewelry.test.csv.gz
      - data/Clothing_Shoes_and_Jewelry.train.csv.gz
      - data/Clothing_Shoes_and_Jewelry.valid.csv.gz
      - data/Electronics.test.csv.gz
      - data/Electronics.train.csv.gz
      - data/Electronics.valid.csv.gz
      - data/Grocery_and_Gourmet_Food.test.csv.gz
      - data/Grocery_and_Gourmet_Food.train.csv.gz
      - data/Grocery_and_Gourmet_Food.valid.csv.gz
      - data/Health_and_Household.test.csv.gz
      - data/Health_and_Household.train.csv.gz
      - data/Health_and_Household.valid.csv.gz
      - data/Home_and_Kitchen.test.csv.gz
      - data/Home_and_Kitchen.train.csv.gz
      - data/Home_and_Kitchen.valid.csv.gz
      - data/Industrial_and_Scientific.test.csv.gz
      - data/Industrial_and_Scientific.train.csv.gz
      - data/Industrial_and_Scientific.valid.csv.gz
      - data/Kindle_Store.test.csv.gz
      - data/Kindle_Store.train.csv.gz
      - data/Kindle_Store.valid.csv.gz
      - data/Movies_and_TV.test.csv.gz
      - data/Movies_and_TV.train.csv.gz
      - data/Movies_and_TV.valid.csv.gz
      - data/Musical_Instruments.test.csv.gz
      - data/Musical_Instruments.train.csv.gz
      - data/Musical_Instruments.valid.csv.gz
      - data/Office_Products.test.csv.gz
      - data/Office_Products.train.csv.gz
      - data/Office_Products.valid.csv.gz
      - data/Patio_Lawn_and_Garden.test.csv.gz
      - data/Patio_Lawn_and_Garden.train.csv.gz
      - data/Patio_Lawn_and_Garden.valid.csv.gz
      - data/Pet_Supplies.test.csv.gz
      - data/Pet_Supplies.train.csv.gz
      - data/Pet_Supplies.valid.csv.gz
      - data/Software.test.csv.gz
      - data/Software.train.csv.gz
      - data/Software.valid.csv.gz
      - data/Sports_and_Outdoors.test.csv.gz
      - data/Sports_and_Outdoors.train.csv.gz
      - data/Sports_and_Outdoors.valid.csv.gz
      - data/Tools_and_Home_Improvement.test.csv.gz
      - data/Tools_and_Home_Improvement.train.csv.gz
      - data/Tools_and_Home_Improvement.valid.csv.gz
      - data/Toys_and_Games.test.csv.gz
      - data/Toys_and_Games.train.csv.gz
      - data/Toys_and_Games.valid.csv.gz
      - data/Video_Games.test.csv.gz
      - data/Video_Games.train.csv.gz
      - data/Video_Games.valid.csv.gz
    outs:
      - user-ids.duckdb
  scan-bench-items:
    cmd: python ../../action.py amazon collect-ids --item -D item-ids.duckdb data
    deps:
      - data/Arts_Crafts_and_Sewing.test.csv.gz
      - data/Arts_Crafts_and_Sewing.train.csv.gz
      - data/Arts_Crafts_and_Sewing.valid.csv.gz
      - data/Automotive.test.csv.gz
      - data/Automotive.train.csv.gz
      - data/Automotive.valid.csv.gz
      - data/Baby_Products.test.csv.gz
      - data/Baby_Products.train.csv.gz
      - data/Baby_Products.valid.csv.gz
      - data/Beauty_and_Personal_Care.test.csv.gz
      - data/Beauty_and_Personal_Care.train.csv.gz
      - data/Beauty_and_Personal_Care.valid.csv.gz
      - data/Books.test.csv.gz
      - data/Books.train.csv.gz
      - data/Books.valid.csv.gz
      - data/CDs_and_Vinyl.test.csv.gz
      - data/CDs_and_Vinyl.train.csv.gz
      - data/CDs_and_Vinyl.valid.csv.gz
      - data/Cell_Phones_and_Accessories.test.csv.gz
      - data/Cell_Phones_and_Accessories.train.csv.gz
      - data/Cell_Phones_and_Accessories.valid.csv.gz
      - data/Clothing_Shoes_and_Jewelry.test.csv.gz
      - data/Clothing_Shoes_and_Jewelry.train.csv.gz
      - data/Clothing_Shoes_and_Jewelry.valid.csv.gz
      - data/Electronics.test.csv.gz
      - data/Electronics.train.csv.gz
      - data/Electronics.valid.csv.gz
      - data/Grocery_and_Gourmet_Food.test.csv.gz
      - data/Grocery_and_Gourmet_Food.train.csv.gz
      - data/Grocery_and_Gourmet_Food.valid.csv.gz
      - data/Health_and_Household.test.csv.gz
      - data/Health_and_Household.train.csv.gz
      - data/Health_and_Household.valid.csv.gz
      - data/Home_and_Kitchen.test.csv.gz
      - data/Home_and_Kitchen.train.csv.gz
      - data/Home_and_Kitchen.valid.csv.gz
      - data/Industrial_and_Scientific.test.csv.gz
      - data/Industrial_and_Scientific.train.csv.gz
      - data/Industrial_and_Scientific.valid.csv.gz
      - data/Kindle_Store.test.csv.gz
      - data/Kindle_Store.train.csv.gz
      - data/Kindle_Store.valid.csv.gz
      - data/Movies_and_TV.test.csv.gz
      - data/Movies_and_TV.train.csv.gz
      - data/Movies_and_TV.valid.csv.gz
      - data/Musical_Instruments.test.csv.gz
      - data/Musical_Instruments.train.csv.gz
      - data/Musical_Instruments.valid.csv.gz
      - data/Office_Products.test.csv.gz
      - data/Office_Products.train.csv.gz
      - data/Office_Products.valid.csv.gz
      - data/Patio_Lawn_and_Garden.test.csv.gz
      - data/Patio_Lawn_and_Garden.train.csv.gz
      - data/Patio_Lawn_and_Garden.valid.csv.gz
      - data/Pet_Supplies.test.csv.gz
      - data/Pet_Supplies.train.csv.gz
      - data/Pet_Supplies.valid.csv.gz
      - data/Software.test.csv.gz
      - data/Software.train.csv.gz
      - data/Software.valid.csv.gz
      - data/Sports_and_Outdoors.test.csv.gz
      - data/Sports_and_Outdoors.train.csv.gz
      - data/Sports_and_Outdoors.valid.csv.gz
      - data/Tools_and_Home_Improvement.test.csv.gz
      - data/Tools_and_Home_Improvement.train.csv.gz
      - data/Tools_and_Home_Improvement.valid.csv.gz
      - data/Toys_and_Games.test.csv.gz
      - data/Toys_and_Games.train.csv.gz
      - data/Toys_and_Games.valid.csv.gz
      - data/Video_Games.test.csv.gz
      - data/Video_Games.train.csv.gz
      - data/Video_Games.valid.csv.gz
    outs:
      - item-ids.duckdb
  convert-ratings:
    foreach:
      - Arts_Crafts_and_Sewing.test
      - Arts_Crafts_and_Sewing.train
      - Arts_Crafts_and_Sewing.valid
      - Automotive.test
      - Automotive.train
      - Automotive.valid
      - Baby_Products.test
      - Baby_Products.train
      - Baby_Products.valid
      - Beauty_and_Personal_Care.test
      - Beauty_and_Personal_Care.train
      - Beauty_and_Personal_Care.valid
      - Books.test
      - Books.train
      - Books.valid
      - CDs_and_Vinyl.test
      - CDs_and_Vinyl.train
      - CDs_and_Vinyl.valid
      - Cell_Phones_and_Accessories.test
      - Cell_Phones_and_Accessories.train
      - Cell_Phones_and_Accessories.valid
      - Clothing_Shoes_and_Jewelry.test
      - Clothing_Shoes_and_Jewelry.train
      - Clothing_Shoes_and_Jewelry.valid
      - Electronics.test
      - Electronics.train
      - Electronics.valid
      - Grocery_and_Gourmet_Food.test
      - Grocery_and_Gourmet_Food.train
      - Grocery_and_Gourmet_Food.valid
      - Health_and_Household.test
      - Health_and_Household.train
      - Health_and_Household.valid
      - Home_and_Kitchen.test
      - Home_and_Kitchen.train
      - Home_and_Kitchen.valid
      - Industrial_and_Scientific.test
      - Industrial_and_Scientific.train
      - Industrial_and_Scientific.valid
      - Kindle_Store.test
      - Kindle_Store.train
      - Kindle_Store.valid
      - Movies_and_TV.test
      - Movies_and_TV.train
      - Movies_and_TV.valid
      - Musical_Instruments.test
      - Musical_Instruments.train
      - Musical_Instruments.valid
      - Office_Products.test
      - Office_Products.train
      - Office_Products.valid
      - Patio_Lawn_and_Garden.test
      - Patio_Lawn_and_Garden.train
      - Patio_Lawn_and_Garden.valid
      - Pet_Supplies.test
      - Pet_Supplies.train
      - Pet_Supplies.valid
      - Software.test
      - Software.train
      - Software.valid
      - Sports_and_Outdoors.test
      - Sports_and_Outdoors.train
      - Sports_and_Outdoors.valid
      - Tools_and_Home_Improvement.test
      - Tools_and_Home_Improvement.train
      - Tools_and_Home_Improvement.valid
      - Toys_and_Games.test
      - Toys_and_Games.train
      - Toys_and_Games.valid
      - Video_Games.test
      - Video_Games.train
      - Video_Games.valid
    do:
      cmd: >-
        python ../../action.py amazon import-bench --users=user-ids.duckdb --items=item-ids.duckdb data/${item}.csv.gz
      deps:
        - user-ids.duckdb
        - item-ids.duckdb
        - 'data/${item}.csv.gz'
      outs:
        - 'data/${item}.parquet'
  export-qrels:
    foreach:
      - Arts_Crafts_and_Sewing.test.csv.gz
      - Automotive.test.csv.gz
      - Baby_Products.test.csv.gz
      - Beauty_and_Personal_Care.test.csv.gz
      - Books.test.csv.gz
      - CDs_and_Vinyl.test.csv.gz
      - Cell_Phones_and_Accessories.test.csv.gz
      - Clothing_Shoes_and_Jewelry.test.csv.gz
      - Electronics.test.csv.gz
      - Grocery_and_Gourmet_Food.test.csv.gz
      - Health_and_Household.test.csv.gz
      - Home_and_Kitchen.test.csv.gz
      - Industrial_and_Scientific.test.csv.gz
      - Kindle_Store.test.csv.gz
      - Movies_and_TV.test.csv.gz
      - Musical_Instruments.test.csv.gz
      - Office_Products.test.csv.gz
      - Patio_Lawn_and_Garden.test.csv.gz
      - Pet_Supplies.test.csv.gz
      - Software.test.csv.gz
      - Sports_and_Outdoors.test.csv.gz
      - Tools_and_Home_Improvement.test.csv.gz
      - Toys_and_Games.test.csv.gz
      - Video_Games.test.csv.gz
    do:
      cmd: 'python ../../action.py trec export qrels data/${item}.parquet'
      deps:
        - 'data/${item}.parquet'
      outs:
        - 'data/${item}.qrels.gz'
  collect-stats:
    cmd: >-
      python ../../action.py run-duck-sql --database=stats.duckdb bench-stats.sql
    outs:
      - stats.duckdb
    deps:
      - bench-stats.sql
      - data/Arts_Crafts_and_Sewing.test.parquet
      - data/Arts_Crafts_and_Sewing.train.parquet
      - data/Arts_Crafts_and_Sewing.valid.parquet
      - data/Automotive.test.parquet
      - data/Automotive.train.parquet
      - data/Automotive.valid.parquet
      - data/Baby_Products.test.parquet
      - data/Baby_Products.train.parquet
      - data/Baby_Products.valid.parquet
      - data/Beauty_and_Personal_Care.test.parquet
      - data/Beauty_and_Personal_Care.train.parquet
      - data/Beauty_and_Personal_Care.valid.parquet
      - data/Books.test.parquet
      - data/Books.train.parquet
      - data/Books.valid.parquet
      - data/CDs_and_Vinyl.test.parquet
      - data/CDs_and_Vinyl.train.parquet
      - data/CDs_and_Vinyl.valid.parquet
      - data/Cell_Phones_and_Accessories.test.parquet
      - data/Cell_Phones_and_Accessories.train.parquet
      - data/Cell_Phones_and_Accessories.valid.parquet
      - data/Clothing_Shoes_and_Jewelry.test.parquet
      - data/Clothing_Shoes_and_Jewelry.train.parquet
      - data/Clothing_Shoes_and_Jewelry.valid.parquet
      - data/Electronics.test.parquet
      - data/Electronics.train.parquet
      - data/Electronics.valid.parquet
      - data/Grocery_and_Gourmet_Food.test.parquet
      - data/Grocery_and_Gourmet_Food.train.parquet
      - data/Grocery_and_Gourmet_Food.valid.parquet
      - data/Health_and_Household.test.parquet
      - data/Health_and_Household.train.parquet
      - data/Health_and_Household.valid.parquet
      - data/Home_and_Kitchen.test.parquet
      - data/Home_and_Kitchen.train.parquet
      - data/Home_and_Kitchen.valid.parquet
      - data/Industrial_and_Scientific.test.parquet
      - data/Industrial_and_Scientific.train.parquet
      - data/Industrial_and_Scientific.valid.parquet
      - data/Kindle_Store.test.parquet
      - data/Kindle_Store.train.parquet
      - data/Kindle_Store.valid.parquet
      - data/Movies_and_TV.test.parquet
      - data/Movies_and_TV.train.parquet
      - data/Movies_and_TV.valid.parquet
      - data/Musical_Instruments.test.parquet
      - data/Musical_Instruments.train.parquet
      - data/Musical_Instruments.valid.parquet
      - data/Office_Products.test.parquet
      - data/Office_Products.train.parquet
      - data/Office_Products.valid.parquet
      - data/Patio_Lawn_and_Garden.test.parquet
      - data/Patio_Lawn_and_Garden.train.parquet
      - data/Patio_Lawn_and_Garden.valid.parquet
      - data/Pet_Supplies.test.parquet
      - data/Pet_Supplies.train.parquet
      - data/Pet_Supplies.valid.parquet
      - data/Software.test.parquet
      - data/Software.train.parquet
      - data/Software.valid.parquet
      - data/Sports_and_Outdoors.test.parquet
      - data/Sports_and_Outdoors.train.parquet
      - data/Sports_and_Outdoors.valid.parquet
      - data/Tools_and_Home_Improvement.test.parquet
      - data/Tools_and_Home_Improvement.train.parquet
      - data/Tools_and_Home_Improvement.valid.parquet
      - data/Toys_and_Games.test.parquet
      - data/Toys_and_Games.train.parquet
      - data/Toys_and_Games.valid.parquet
      - data/Video_Games.test.parquet
      - data/Video_Games.train.parquet
      - data/Video_Games.valid.parquet
  run-default-Bias-test:
    foreach: &ref_0
      - Arts_Crafts_and_Sewing
      - Automotive
      - Baby_Products
      - Beauty_and_Personal_Care
      - Books
      - CDs_and_Vinyl
      - Cell_Phones_and_Accessories
      - Clothing_Shoes_and_Jewelry
      - Electronics
      - Grocery_and_Gourmet_Food
      - Health_and_Household
      - Home_and_Kitchen
      - Industrial_and_Scientific
      - Kindle_Store
      - Movies_and_TV
      - Musical_Instruments
      - Office_Products
      - Patio_Lawn_and_Garden
      - Pet_Supplies
      - Software
      - Sports_and_Outdoors
      - Tools_and_Home_Improvement
      - Toys_and_Games
      - Video_Games
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/Bias.duckdb Bias
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/Bias.duckdb'
  run-default-Popular-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/Popular.duckdb Popular
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/Popular.duckdb'
  run-default-BiasedMF-ALS-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/BiasedMF-ALS.duckdb BiasedMF-ALS
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/BiasedMF-ALS.duckdb'
  run-default-ImplicitMF-ALS-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/ImplicitMF-ALS.duckdb ImplicitMF-ALS
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/ImplicitMF-ALS.duckdb'
  run-default-IKNN-Explicit-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/IKNN-Explicit.duckdb IKNN-Explicit
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/IKNN-Explicit.duckdb'
  run-default-IKNN-Implicit-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/IKNN-Implicit.duckdb IKNN-Implicit
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/IKNN-Implicit.duckdb'
  run-default-Implicit-BPR-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/Implicit-BPR.duckdb Implicit-BPR
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/Implicit-BPR.duckdb'
  run-default-HPF-test:
    foreach: *ref_0
    do:
      cmd: >-
        python ../../action.py generate --default --train=data/${item}.train.parquet --train=data/${item}.valid.parquet --test=data/${item}.test.parquet -o runs/default/${item}/HPF.duckdb HPF
      deps:
        - 'data/${item}.train.parquet'
        - 'data/${item}.valid.parquet'
        - 'data/${item}.test.parquet'
      outs:
        - 'runs/default/${item}/HPF.duckdb'
