stages:
  import-bench:
    foreach:
      - Arts_Crafts_and_Sewing
      - Automotive
      - Baby_Products
      - Beauty_and_Personal_Care
      - Books
      - CDs_and_Vinyl
      - Cell_Phones_and_Accessories
      - Clothing_Shoes_and_Jewelry
      - Electronics
      - Grocery_and_Gourmet_Food
      - Health_and_Household
      - Home_and_Kitchen
      - Industrial_and_Scientific
      - Kindle_Store
      - Movies_and_TV
      - Musical_Instruments
      - Office_Products
      - Patio_Lawn_and_Garden
      - Pet_Supplies
      - Software
      - Sports_and_Outdoors
      - Tools_and_Home_Improvement
      - Toys_and_Games
      - Video_Games
    do:
      cmd: 'python ../import-az.py --benchmark data/${item}'
      deps:
        - 'data/${item}.train.csv.gz'
        - 'data/${item}.valid.csv.gz'
        - 'data/${item}.test.csv.gz'
      outs:
        - 'data/${item}.duckdb'
