scorer = "lenskit.basic:BiasScorer"
predictor = true

[default]
damping = 50

[search.grid]
user_damping = [0, 5, 10, 25]
item_damping = [0, 5, 10, 25]

[search.params.user_damping]
type = "real"
min = 0
max = 100
space = "logarithmic"

[search.params.item_damping]
type = "real"
min = 1
max = 100
space = "logarithmic"
