scorer = "lenskit.als:ImplicitMFScorer"

[default]
features = 50

[search.grid]
features = [5, 10, 15, 25, 35, 50, 75, 100, 150, 250]
reg = [0.01, 0.1, 1.0]

[search.params.features]
type = "integer"
min = 5
max = 500
space = "logarithmic"

[search.params.reg]
type = "real"
min = 1.0e-9
max = 10
space = "logarithmic"
tuple = 2

[search.params.weight]
type = "real"
min = 1
max = 100
space = "linear"

[search.params.epochs]
type = "integer"
min = 5
max = 50
